/**
 * Svájci Kvíz — kérdés-bank.
 *
 * Cél: napi 3 kérdéses tudás-tréning a magyar-svájci közösségnek. Témák:
 * földrajz, történelem, kultúra, ünnepek, kantonok, nyelv, étel, közlekedés,
 * intézmények, mindennapok.
 *
 * Minden kérdés 4 választást + 1 helyes választ tartalmaz, plus magyarázat
 * a válaszhoz (a sikeres válasz után jelenik meg).
 */

export type QuizCategory =
  | "geography"
  | "history"
  | "culture"
  | "language"
  | "food"
  | "transport"
  | "institutions"
  | "everyday";

export interface QuizQuestion {
  id: string;
  category: QuizCategory;
  question: string;
  options: [string, string, string, string];
  /** Helyes válasz index-e (0-3). */
  correct: 0 | 1 | 2 | 3;
  /** Magyarázat — a válasz után jelenik meg. */
  explanation: string;
}

export const QUIZ_CATEGORY_META: Record<QuizCategory, { label: string; emoji: string }> = {
  geography:    { label: "Földrajz",       emoji: "🗺️" },
  history:      { label: "Történelem",     emoji: "📜" },
  culture:      { label: "Kultúra",        emoji: "🎭" },
  language:     { label: "Nyelv",          emoji: "💬" },
  food:         { label: "Étel & ital",    emoji: "🍽️" },
  transport:    { label: "Közlekedés",     emoji: "🚆" },
  institutions: { label: "Intézmények",    emoji: "🏛️" },
  everyday:     { label: "Hétköznapok",    emoji: "🇨🇭" },
};

export const QUIZ_BANK: QuizQuestion[] = [
  // === FÖLDRAJZ ===
  {
    id: "geo-cantons",
    category: "geography",
    question: "Hány kantonja van Svájcnak?",
    options: ["20", "22", "26", "28"],
    correct: 2,
    explanation: "Svájcnak 26 kantonja van — pontosabban 20 teljes kanton és 6 fél-kanton.",
  },
  {
    id: "geo-capital",
    category: "geography",
    question: "Mi Svájc fővárosa?",
    options: ["Zürich", "Genf", "Bern", "Basel"],
    correct: 2,
    explanation: "Bern a 'Bundesstadt' (szövetségi főváros) — bár a legnagyobb város Zürich.",
  },
  {
    id: "geo-largest-city",
    category: "geography",
    question: "Melyik a legnagyobb svájci város népességszám szerint?",
    options: ["Bern", "Zürich", "Basel", "Genf"],
    correct: 1,
    explanation: "Zürich kb. 440 000 fős — a legnagyobb város. A főváros viszont Bern.",
  },
  {
    id: "geo-matterhorn",
    category: "geography",
    question: "Hány méter magas a Matterhorn?",
    options: ["3 998 m", "4 478 m", "4 634 m", "4 810 m"],
    correct: 1,
    explanation: "A Matterhorn 4 478 m magas — de NEM ez a legmagasabb svájci csúcs.",
  },
  {
    id: "geo-dufourspitze",
    category: "geography",
    question: "Melyik a legmagasabb svájci csúcs?",
    options: ["Matterhorn", "Eiger", "Dufourspitze", "Jungfrau"],
    correct: 2,
    explanation: "A Dufourspitze a Monte Rosa-masszívumban — 4 634 m. A Matterhorn 'csak' 4 478 m.",
  },
  {
    id: "geo-largest-canton",
    category: "geography",
    question: "Melyik a legnagyobb kanton terület szerint?",
    options: ["Bern", "Graubünden", "Wallis", "Zürich"],
    correct: 1,
    explanation: "Graubünden (GR) a legnagyobb kanton — 7 105 km². Nyelvileg is különleges: 3 hivatalos nyelv (DE/IT/RM).",
  },
  {
    id: "geo-most-populated",
    category: "geography",
    question: "Melyik a legnépesebb kanton?",
    options: ["Bern", "Zürich", "Waadt", "Aargau"],
    correct: 1,
    explanation: "Zürich kanton kb. 1.6 millió lakossal — a legnépesebb.",
  },
  {
    id: "geo-rivers",
    category: "geography",
    question: "Melyik folyó NEM ered Svájcban?",
    options: ["Rajna", "Rhône", "Duna", "Inn"],
    correct: 2,
    explanation: "A Duna NEM eredete Svájcnak — Németországban, a Fekete-erdőben ered. A Rajna, a Rhône és az Inn viszont igen.",
  },
  {
    id: "geo-borders",
    category: "geography",
    question: "Hány országgal határos Svájc?",
    options: ["3", "4", "5", "6"],
    correct: 2,
    explanation: "5 országgal: Németország, Franciaország, Olaszország, Ausztria, Liechtenstein.",
  },

  // === TÖRTÉNELEM ===
  {
    id: "his-foundation",
    category: "history",
    question: "Mikor alakult meg a Svájci Konföderáció (eredeti szövetség)?",
    options: ["1291", "1389", "1492", "1648"],
    correct: 0,
    explanation: "1291 augusztus 1. — a Rütli-eskü napja. Uri, Schwyz és Unterwalden szövetsége. Ezért nemzeti ünnep aug. 1.",
  },
  {
    id: "his-eu",
    category: "history",
    question: "Mikor lépett be Svájc az EU-ba?",
    options: ["1995", "2002", "2014", "Soha"],
    correct: 3,
    explanation: "Svájc NEM tagja az EU-nak. Számos kétoldalú megállapodással integrálódik, de teljes tagja sosem volt.",
  },
  {
    id: "his-neutrality",
    category: "history",
    question: "Mióta semleges hivatalosan Svájc?",
    options: ["1648 (vesztfáliai béke)", "1815 (bécsi kongresszus)", "1914", "1945"],
    correct: 1,
    explanation: "Az 1815-ös bécsi kongresszus hivatalosan elismerte Svájc örökös semlegességét.",
  },
  {
    id: "his-women-vote",
    category: "history",
    question: "Mikor kaptak választójogot a svájci nők szövetségi szinten?",
    options: ["1918", "1945", "1971", "1990"],
    correct: 2,
    explanation: "1971 — meglepően későn. Appenzell Innerrhoden-ben csak 1990-ben kantoni szinten.",
  },
  {
    id: "his-un",
    category: "history",
    question: "Mikor lett Svájc ENSZ-tag?",
    options: ["1945", "1990", "2002", "2014"],
    correct: 2,
    explanation: "2002. Népszavazáson döntöttek — Svájc volt az utolsó nagy európai ország ami csatlakozott.",
  },

  // === KULTÚRA / ÜNNEPEK ===
  {
    id: "cul-national-day",
    category: "culture",
    question: "Mikor van Svájc nemzeti ünnepe?",
    options: ["Július 14.", "Augusztus 1.", "Szeptember 21.", "December 6."],
    correct: 1,
    explanation: "Augusztus 1. — az 1291-es Rütli-eskü évfordulója. Tűzijáték, máglyák, népi ünnep.",
  },
  {
    id: "cul-sechselauten",
    category: "culture",
    question: "Mi a Sechseläuten?",
    options: [
      "Zürichi tavaszi ünnep, télbúcsúztató",
      "Bázeli farsang",
      "Genfi karácsonyi piac",
      "Berni hagyományos ló-verseny",
    ],
    correct: 0,
    explanation: "Zürichi tavaszi ünnep áprilisban — a 'Böögg' (hóember-szerű figura) elégetése jelképesen elűzi a telet.",
  },
  {
    id: "cul-fasnacht",
    category: "culture",
    question: "Hol tartják Svájc leghíresebb farsangját?",
    options: ["Genf", "Luzern", "Bázel", "Bern"],
    correct: 2,
    explanation: "Bázelben — a 'Basler Fasnacht' UNESCO-örökség. Három nap, hajnali 4-kor kezdődik a 'Morgestraich'.",
  },
  {
    id: "cul-flag",
    category: "culture",
    question: "Milyen alakú a svájci zászló?",
    options: ["Téglalap", "Négyzet", "Háromszög", "Pajzs"],
    correct: 1,
    explanation: "Svájc és a Vatikán az egyetlen két ország, aminek NÉGYZET alakú a zászlója.",
  },
  {
    id: "cul-cross",
    category: "culture",
    question: "Mit jelképez a svájci zászló fehér keresztje?",
    options: [
      "A katolikus egyházat",
      "A semlegességet",
      "A Konföderáció hagyományos jelképét",
      "A négy nemzeti nyelvet",
    ],
    correct: 2,
    explanation: "A keresztet a középkor óta használják a svájci konföderációs csapatok megkülönböztetésére. A Vörös Kereszt szervezet (1863) fordítottja erre.",
  },

  // === NYELV ===
  {
    id: "lang-official",
    category: "language",
    question: "Hány hivatalos nyelve van Svájcnak?",
    options: ["2", "3", "4", "5"],
    correct: 2,
    explanation: "4: német (kb. 62%), francia (23%), olasz (8%), retoromán (0.5%).",
  },
  {
    id: "lang-rumantsch",
    category: "language",
    question: "Melyik kantonban beszélnek hivatalosan retorománul?",
    options: ["Tessin", "Wallis", "Graubünden", "Jura"],
    correct: 2,
    explanation: "Graubünden — az egyetlen hivatalosan három-nyelvű kanton: német, olasz, retoromán.",
  },
  {
    id: "lang-gruezi",
    category: "language",
    question: "Mit jelent a 'Grüezi'?",
    options: ["Köszönöm", "Helló (német-svájci)", "Bocsánat", "Viszlát"],
    correct: 1,
    explanation: "A 'Grüezi' a svájci-német köszönés ('Adj' Isten' jellegű). 'Salü' baráti, 'Adieu' francia területen.",
  },
  {
    id: "lang-rostigraben",
    category: "language",
    question: "Mi az a 'Röstigraben'?",
    options: [
      "Egy hegyvonulat a kantonok közt",
      "A német- és francia-ajkú régiók közti kulturális határvonal",
      "Egy hagyományos étel",
      "Egy folyó-szakasz",
    ],
    correct: 1,
    explanation: "Az image alak a Saane / Sarine folyó mentén — szimbolikus kulturális határ a Deutschschweiz és a Romandie közt.",
  },
  {
    id: "lang-velo",
    category: "language",
    question: "Mit jelent a 'Velo'?",
    options: ["Autó", "Kerékpár", "Vonat", "Sí"],
    correct: 1,
    explanation: "Svájc-németben 'Velo' = bicikli (a francia 'vélocipède' rövidítéséből). Németországban 'Fahrrad'.",
  },

  // === ÉTEL / ITAL ===
  {
    id: "food-fondue",
    category: "food",
    question: "Miből készül a klasszikus svájci fondue?",
    options: [
      "Csak Emmentaler sajtból",
      "Gruyère + Vacherin sajtokból fehérborral",
      "Sajt + tej + tojás",
      "Olvasztott vajból",
    ],
    correct: 1,
    explanation: "Klasszikus 'fondue moitié-moitié' = fele Gruyère + fele Vacherin Fribourgeois, fehérborral és kis kirsch-sel.",
  },
  {
    id: "food-rosti",
    category: "food",
    question: "Mi a Rösti?",
    options: [
      "Sajtos pirított krumpli",
      "Sárgarépás leves",
      "Disznóhús salátával",
      "Sajt-szendvics",
    ],
    correct: 0,
    explanation: "Reszelt és pirított krumpli (mint a hash brown). Klasszikus svájci-német köret, főleg Berni-Solothurn körül.",
  },
  {
    id: "food-raclette",
    category: "food",
    question: "Mi a Raclette?",
    options: [
      "Egy sajt-fajta + a róla nevezett étel (olvasztott sajt krumplival, savanyúsággal)",
      "Egyfajta száraz kolbász",
      "Csokis fondue",
      "Tej-leves",
    ],
    correct: 0,
    explanation: "Wallisi eredetű sajt — kis vasalót használva felolvasztják és krumplira, savanyúságra teszik.",
  },
  {
    id: "food-cervelat",
    category: "food",
    question: "Mi a 'Cervelat'?",
    options: ["Sajt", "Svájci nemzeti kolbász", "Bor-fajta", "Pékáru"],
    correct: 1,
    explanation: "A 'svájci nemzeti kolbász' — főtt-füstölt, marhabél-burkolatban. Tipikusan kettéhasítva grillen sütik.",
  },
  {
    id: "food-toblerone",
    category: "food",
    question: "Melyik svájci város a Toblerone csoki szülőhelye?",
    options: ["Genf", "Zürich", "Bern", "Lausanne"],
    correct: 2,
    explanation: "Bern — 1908-ban Theodor Tobler alkotta. A háromszög-alak a Matterhorn-ra utal.",
  },
  {
    id: "food-rivella",
    category: "food",
    question: "Miből készül a Rivella üdítő?",
    options: ["Tejből", "Tejsavóból", "Almából", "Borból"],
    correct: 1,
    explanation: "Tejsavóból (Molke) — 1952 óta gyártják. Tipikus svájci 'kerékpáros' ital.",
  },

  // === KÖZLEKEDÉS ===
  {
    id: "trans-sbb",
    category: "transport",
    question: "Mi az SBB?",
    options: ["Svájci Bankárszövetség", "Svájci Bizottság", "Svájci Szövetségi Vasút", "Svájci Bor-szervezet"],
    correct: 2,
    explanation: "Schweizerische Bundesbahnen (SBB / CFF / FFS) — a svájci vasúttársaság. Pontos, sűrű, drága.",
  },
  {
    id: "trans-halbtax",
    category: "transport",
    question: "Mit ad a 'Halbtax' kártya?",
    options: [
      "Ingyen utazást",
      "50% kedvezményt vonaton, buszon, hajón",
      "Csak kantoni utazásra",
      "Csak hétvégén",
    ],
    correct: 1,
    explanation: "50% kedvezmény szinte minden tömegközlekedésre. Éves 170 CHF — ha sokat utazol, hamar megtérül.",
  },
  {
    id: "trans-ga",
    category: "transport",
    question: "Mit ad a 'GA' (Generalabonnement)?",
    options: [
      "Csak a vonatokon szabad utazás",
      "Korlátlan utazás minden SBB + buszon + hajón + sok hegyivasúton",
      "Csak a hegyi-vonatok",
      "Csak Zürich kantonban",
    ],
    correct: 1,
    explanation: "Évente kb. 3 860 CHF (felnőtt 2. osztály). Korlátlan utazás — drága, de mindenki esküszik rá.",
  },
  {
    id: "trans-postauto",
    category: "transport",
    question: "Mi a 'PostAuto'?",
    options: [
      "Posta-kézbesítő autó",
      "Sárga svájci poszta-busz, főleg hegyi-utakra",
      "Helyi taxi",
      "Postai pénzátutalás",
    ],
    correct: 1,
    explanation: "A sárga PostAuto-k mennek oda is, ahova a vonat nem — kis falvakba, hegyekbe. Az SBB partnere.",
  },
  {
    id: "trans-license",
    category: "transport",
    question: "Mennyi időn belül kell magyar jogosítványt svájcira cserélni?",
    options: ["3 hónap", "6 hónap", "12 hónap", "24 hónap"],
    correct: 2,
    explanation: "12 hónap a Svájcba érkezéstől. Vizsga nem kell — papíralapú eljárás a Strassenverkehrsamt-on.",
  },

  // === INTÉZMÉNYEK ===
  {
    id: "inst-ahv",
    category: "institutions",
    question: "Mi az AHV?",
    options: [
      "Egészségbiztosítás",
      "Öregségi nyugdíj-biztosítás",
      "Munkanélküli-segély",
      "Lakásépítési alap",
    ],
    correct: 1,
    explanation: "Alters- und Hinterlassenenversicherung — az állami nyugdíj-rendszer (1. piller).",
  },
  {
    id: "inst-eth",
    category: "institutions",
    question: "Mi az ETH Zürich?",
    options: [
      "Zürich városi egyetem",
      "Szövetségi műszaki egyetem",
      "Magán pénzügyi főiskola",
      "Természetgyógyász egyetem",
    ],
    correct: 1,
    explanation: "Eidgenössische Technische Hochschule — Einstein, Pauli, Röntgen iskolája. A világ top 10 egyetemei közt.",
  },
  {
    id: "inst-bag",
    category: "institutions",
    question: "Mi a BAG?",
    options: [
      "Bizalmasok Akciós Gyűlése",
      "Bundesamt für Gesundheit — Egészségügyi Hivatal",
      "Bázeli Akadémia",
      "Berni Adóhivatal",
    ],
    correct: 1,
    explanation: "Bundesamt für Gesundheit — a szövetségi egészségügyi hivatal. Covid-idején vált ismertté.",
  },
  {
    id: "inst-suva",
    category: "institutions",
    question: "Mi a SUVA?",
    options: [
      "Svájci hadsereg",
      "Baleseti biztosító (Schweizerische Unfallversicherungsanstalt)",
      "Bevándorlási hivatal",
      "Diákszervezet",
    ],
    correct: 1,
    explanation: "Schweizerische Unfallversicherungsanstalt — kötelező baleseti biztosító a munkavállalóknak.",
  },
  {
    id: "inst-quellensteuer",
    category: "institutions",
    question: "Mi a Quellensteuer?",
    options: [
      "Forrásadó — a bér-ből automatikusan levont adó",
      "Vízszolgáltatási díj",
      "Sport-egyesületi tagdíj",
      "Helyi parkolási bírság",
    ],
    correct: 0,
    explanation: "A B-engedélyes külföldiek bérét forrás-adózással terhelik. A munkáltató automatikusan vonja le és átutalja.",
  },
  {
    id: "inst-3a",
    category: "institutions",
    question: "Mi a '3a-piller'?",
    options: [
      "Magán nyugdíj-megtakarítás adómentesen",
      "Egészségbiztosítás kiegészítés",
      "Lakhatási támogatás",
      "Munkáltatói bónusz",
    ],
    correct: 0,
    explanation: "A 3. piller 'a' része — adómentes magán nyugdíj-megtakarítás. Max 7 056 CHF/év 2024-ben (alkalmazottaknak).",
  },

  // === HÉTKÖZNAPOK ===
  {
    id: "ev-currency",
    category: "everyday",
    question: "Milyen pénznem hivatalos Svájcban?",
    options: ["Euro", "Svájci frank (CHF)", "Schilling", "Euro és CHF egyszerre"],
    correct: 1,
    explanation: "Svájci frank (CHF) — szinte mindenhol elfogadnak EUR-t is, de visszajárót CHF-ben adnak.",
  },
  {
    id: "ev-postcode",
    category: "everyday",
    question: "Hány számjegyű egy svájci irányítószám?",
    options: ["3", "4", "5", "6"],
    correct: 1,
    explanation: "4 számjegy. Pl. 8001 Zürich, 3000 Bern, 1000 Lausanne.",
  },
  {
    id: "ev-numberplate",
    category: "everyday",
    question: "Mit jelez a rendszámtábla első része (pl. ZH, BE, GE)?",
    options: ["Évjárat", "Modell", "Kanton", "Tulajdonos kora"],
    correct: 2,
    explanation: "A kanton ahol a kocsi regisztrálva van. Pl. ZH = Zürich, BE = Bern, TI = Ticino.",
  },
  {
    id: "ev-recycling",
    category: "everyday",
    question: "Mi a 'Gebührensack'?",
    options: [
      "Egy díjas hivatalos szemeteszsák — különben bírságot kapsz",
      "Bevásárló-szatyor",
      "Adózási iratcsomó",
      "Postai csomag-doboz",
    ],
    correct: 0,
    explanation: "Sok kantonban (ZH, BE, BS, AG) speciális, díjas zsákba kell tenni a szemetet. Normál zsákban hagyni = 200+ CHF bírság.",
  },
  {
    id: "ev-sunday",
    category: "everyday",
    question: "Mit nem szabad vasárnap Svájcban?",
    options: [
      "Sétálni az utcán",
      "Hangos házimunkát végezni (fűnyírás, fúrás, mosógép)",
      "Bevásárolni a benzinkutaknál",
      "Kerékpározni",
    ],
    correct: 1,
    explanation: "'Sonntagsruhe' — vasárnap a lakókörnyezetben tilos a hangos tevékenység (fűnyírás, fúrás, hangos beszéd). A szomszéd feljelenthet.",
  },
  {
    id: "ev-recycling-pet",
    category: "everyday",
    question: "Hol gyűjtik a PET-palackokat?",
    options: [
      "Csak a magán-szelektív házaknál",
      "A boltokban (Migros, Coop) ingyen visszadobható",
      "Csak az újrahasznosító központokban",
      "A normál szemetesbe is mehet",
    ],
    correct: 1,
    explanation: "Minden Migros/Coop-ban van PET-gyűjtő. Ingyenes, kötelező visszahozni a betétdíjas nem-betétdíjasokat sem dobjuk a normál szemétbe.",
  },

  // ========== KIBŐVÍTÉS 45 → 100 ==========

  // === FÖLDRAJZ +10 ===
  {
    id: "geo-gotthard",
    category: "geography",
    question: "Mi a leghosszabb svájci alagút?",
    options: ["Lötschberg", "Gotthard-bázisalagút", "Furka", "Simplon"],
    correct: 1,
    explanation: "A Gotthard-bázisalagút (vasúti) 57.1 km — a világ leghosszabb vasúti alagútja. 2016-ban nyílt meg.",
  },
  {
    id: "geo-jungfraujoch",
    category: "geography",
    question: "Mi a 'Top of Europe'?",
    options: ["Matterhorn-csúcs", "Jungfraujoch", "Pilatus", "Säntis"],
    correct: 1,
    explanation: "A Jungfraujoch (3 454 m) — Európa legmagasabban fekvő vasúti megállója. Fogaskerekű vonattal megközelíthető.",
  },
  {
    id: "geo-largest-lake-fully-swiss",
    category: "geography",
    question: "Melyik a legnagyobb teljesen svájci tó?",
    options: ["Genfi-tó", "Neuchâteli-tó", "Bodeni-tó", "Zürichi-tó"],
    correct: 1,
    explanation: "A Neuchâteli-tó 218 km² — egyedüli a TOP-3 tóban, ami teljesen svájci. A Genfi és a Bodeni határos.",
  },
  {
    id: "geo-rhine-source",
    category: "geography",
    question: "Hol ered a Rajna?",
    options: [
      "Wallis (Rhône-mellett)",
      "Graubünden — két forrás (Vorder- és Hinterrhein)",
      "Bodeni-tóban",
      "Bernben, az Aaréből",
    ],
    correct: 1,
    explanation: "A Rajna két forrásból ered Graubünden-ben — a Vorderrhein és a Hinterrhein Reichenau-nál egyesülnek.",
  },
  {
    id: "geo-smallest-canton",
    category: "geography",
    question: "Melyik a legkisebb (teljes) kanton terület szerint?",
    options: ["Zug", "Basel-Stadt", "Appenzell Innerrhoden", "Genf"],
    correct: 1,
    explanation: "Basel-Stadt 37 km² — a legkisebb teljes kanton. Lakosság szerint Appenzell IR a legkisebb.",
  },
  {
    id: "geo-tessin-language",
    category: "geography",
    question: "Melyik kanton olasz-ajkú többségben?",
    options: ["Wallis", "Graubünden", "Tessin (Ticino)", "Jura"],
    correct: 2,
    explanation: "Tessin (Ticino) — kb. 350 000 lakos, 80%-uk olasz anyanyelvű. A Lago Maggiore és Lugano itt találhatóak.",
  },
  {
    id: "geo-glaciers",
    category: "geography",
    question: "Hány gleccser található Svájcban (kb.)?",
    options: ["100", "500", "1500", "3000"],
    correct: 2,
    explanation: "Kb. 1 500 gleccser. Az Aletsch a legnagyobb (kb. 20 km hosszú). A klímaváltozás miatt évente zsugorodnak.",
  },
  {
    id: "geo-area",
    category: "geography",
    question: "Mekkora Svájc területe?",
    options: ["31 000 km²", "41 000 km²", "51 000 km²", "61 000 km²"],
    correct: 1,
    explanation: "41 285 km² — kb. Magyarország fele.",
  },
  {
    id: "geo-population",
    category: "geography",
    question: "Hány lakosa van Svájcnak (kb.)?",
    options: ["6 millió", "7.5 millió", "8.9 millió", "11 millió"],
    correct: 2,
    explanation: "Kb. 8.9 millió (2024). Ebből 25% külföldi származású.",
  },
  {
    id: "geo-lake-geneva",
    category: "geography",
    question: "Melyik országokat osztja meg a Genfi-tó?",
    options: ["CH-FR", "CH-IT", "CH-DE", "CH-AT"],
    correct: 0,
    explanation: "A Genfi-tó (Léman) észak-Svájc és Franciaország közt fekszik. A déli partja francia.",
  },

  // === TÖRTÉNELEM +8 ===
  {
    id: "his-tell",
    category: "history",
    question: "Ki volt Wilhelm Tell?",
    options: [
      "Egy 18. századi politikus",
      "A svájci szabadságharc legendás hőse (almát lőtt a fia fejéről)",
      "Egy bankár az 1800-as években",
      "A Vörös Kereszt alapítója",
    ],
    correct: 1,
    explanation: "Legendás 14. századi alak — Uri kantonban élt. Gessler helytartó követelte hogy lőjjön almát a fia fejéről. A modern Schiller-feldolgozás tette híressé.",
  },
  {
    id: "his-dunant",
    category: "history",
    question: "Ki alapította a Vörös Keresztet?",
    options: ["Albert Einstein", "Henri Dunant", "Carl Jung", "Alfred Nobel"],
    correct: 1,
    explanation: "Henri Dunant (genfi üzletember) — 1863-ban alapította a Solferinói csata után. Első Nobel-békedíjas (1901).",
  },
  {
    id: "his-bern-capital",
    category: "history",
    question: "Mikor lett Bern Svájc hivatalos fővárosa?",
    options: ["1291", "1848", "1874", "1948"],
    correct: 1,
    explanation: "1848 — az első modern svájci alkotmány elfogadásakor. Előtte rotáltak a kantonok közt.",
  },
  {
    id: "his-civil-war",
    category: "history",
    question: "Mikor zajlott az utolsó svájci polgárháború (Sonderbundskrieg)?",
    options: ["1798", "1847", "1871", "1914"],
    correct: 1,
    explanation: "1847 — 27 napos rövid háború a katolikus kantonok különszövetsége ellen. Ez vezetett az 1848-as alkotmányhoz.",
  },
  {
    id: "his-chf",
    category: "history",
    question: "Mikor vezették be a svájci frankot (CHF)?",
    options: ["1815", "1850", "1900", "1945"],
    correct: 1,
    explanation: "1850 — az 1848-as alkotmány után, az addig kantononként különböző érméket egységesítette.",
  },
  {
    id: "his-schengen",
    category: "history",
    question: "Mikor csatlakozott Svájc a Schengeni-övezethez?",
    options: ["1995", "2002", "2008", "2014"],
    correct: 2,
    explanation: "2008. december 12. — népszavazáson döntöttek. Schengeni-tag (szabad utazás), de NEM EU-tag.",
  },
  {
    id: "his-banking-secret",
    category: "history",
    question: "Mikor szűnt meg a klasszikus svájci banktitok külföldieknek?",
    options: ["2000", "2009", "2017", "Sosem"],
    correct: 2,
    explanation: "2017-től automatikus adatcsere (AEOI / CRS) az OECD-országokkal — a klasszikus 'névtelen' banki konstrukció megszűnt.",
  },
  {
    id: "his-banks-saved",
    category: "history",
    question: "Hány nyelvet beszéltek hivatalosan 1848-ban Svájcban?",
    options: ["1", "2", "3", "4"],
    correct: 2,
    explanation: "3 — német, francia, olasz. A retoromán 1938-tól kapott hivatalos státuszt.",
  },

  // === KULTÚRA +8 ===
  {
    id: "cul-federer",
    category: "culture",
    question: "Hány Grand Slam-et nyert Roger Federer?",
    options: ["18", "20", "22", "24"],
    correct: 1,
    explanation: "20 Grand Slam — visszavonulásakor (2022) a 2. legtöbb (Nadal 22, Djokovic azóta elhagyta).",
  },
  {
    id: "cul-heidi",
    category: "culture",
    question: "Ki írta a Heidi gyerekkönyvet?",
    options: ["Astrid Lindgren", "Johanna Spyri", "Selma Lagerlöf", "Frances Hodgson Burnett"],
    correct: 1,
    explanation: "Johanna Spyri svájci író — 1880-ban jelent meg. Graubünden-i hegyvidék története.",
  },
  {
    id: "cul-boog",
    category: "culture",
    question: "Mi a 'Böögg'?",
    options: [
      "Egy hagyományos zürichi sütemény",
      "Hóember-figura, amit a Sechseläuten-en elégetnek (időjárás-jóslat)",
      "Egy népi hangszer",
      "Egy gyerekjáték",
    ],
    correct: 1,
    explanation: "A Böögg-öt fűre rakott máglyán égetik el — minél gyorsabb robban, annál szebb a nyár (állítólag).",
  },
  {
    id: "cul-knabenschiessen",
    category: "culture",
    question: "Mi a 'Knabenschiessen'?",
    options: [
      "Zürichi gyerek-lövészverseny és vásár (szeptember)",
      "Berni báli szezon",
      "Téli sporthét Davosban",
      "Tessin-i vendéglátós-fesztivál",
    ],
    correct: 0,
    explanation: "Több száz éves zürichi tradíció — 13-17 éves diákok lőnek. A városban 3 napos vásár + óriáskerék.",
  },
  {
    id: "cul-yodel",
    category: "culture",
    question: "Honnan ered a jodli (Jodel) hagyomány?",
    options: [
      "Olasz Alpokból",
      "Svájci-Bajor-Osztrák hegyvidékről (pásztorok kommunikációja)",
      "Skandináviából",
      "Provence-ből",
    ],
    correct: 1,
    explanation: "Az alpesi pásztorok jelszó-rendszere — szólista hagyomány a Svájci-Bajor-Osztrák régiókban.",
  },
  {
    id: "cul-nobel",
    category: "culture",
    question: "Kb. hány Nobel-díjas van svájci kötődéssel?",
    options: ["10", "30", "50+", "100+"],
    correct: 2,
    explanation: "Több mint 50 — Albert Einstein, Carl Jung, Hermann Hesse, ETH-s tudósok. Egy főre vetítve világrekord.",
  },
  {
    id: "cul-davos",
    category: "culture",
    question: "Miről híres Davos városa?",
    options: [
      "Síparadicsom + World Economic Forum (WEF)",
      "A legnagyobb svájci sajtüzem",
      "ENSZ központja",
      "Olimpiai Múzeum",
    ],
    correct: 0,
    explanation: "Davos: sípálya + a WEF (Davosi Világgazdasági Fórum) éves találkozója januárban.",
  },
  {
    id: "cul-yodel-fest",
    category: "culture",
    question: "Mi az 'Eidgenössisches Schwing- und Älplerfest'?",
    options: [
      "Egy svájci-bajor sörfesztivál",
      "Hárosévente megrendezett országos hagyományos sport-fesztivál (Schwingen, kőzdobás, jodli)",
      "Tessin-i borfesztivál",
      "Zürichi divathét",
    ],
    correct: 1,
    explanation: "A 'Schwingen' (alpesi birkózás), kőzdobás (Steinstossen), jodli, alphorn — a legnagyobb svájci népi sportünnep.",
  },

  // === NYELV +6 ===
  {
    id: "lang-chuchichaeschtli",
    category: "language",
    question: "Mit jelent 'Chuchichäschtli'?",
    options: [
      "Egy hagyományos kalács",
      "Konyhaszekrény (svájci-német, klasszikus 'mondjuk ki' próba)",
      "Egy táncos népi öltözet",
      "Egy gyerekjáték neve",
    ],
    correct: 1,
    explanation: "'Konyhaszekrény' — torokhangos 'ch'-kel. Klasszikus teszt arra, ki tud svájci-németül beszélni.",
  },
  {
    id: "lang-salu",
    category: "language",
    question: "Mit jelent 'Salü' a svájci köszönésben?",
    options: ["Köszönöm szépen", "Szia (baráti)", "Bocsánat", "Egészségedre"],
    correct: 1,
    explanation: "Baráti köszönés ('szia') — francia eredetű ('Salut'), a Deutschschweiz-ban is használják.",
  },
  {
    id: "lang-bahnhof",
    category: "language",
    question: "Mit jelent a 'Bahnhof'?",
    options: ["Postaláda", "Vasútállomás", "Templomtorony", "Bank"],
    correct: 1,
    explanation: "Vasútállomás. (Általános német szó, nem svájci-specifikus.) Pl. Hauptbahnhof = főpályaudvar.",
  },
  {
    id: "lang-migros-meaning",
    category: "language",
    question: "Honnan kapta a nevét a Migros bolt-lánc?",
    options: [
      "Egy alapító család nevéből",
      "A francia 'demi-gros' (félnagykereskedelmi) szóból",
      "A német 'Mit grossen' (nagyokkal)-ból",
      "Egy svájci falu nevéből",
    ],
    correct: 1,
    explanation: "Gottlieb Duttweiler 1925-ben alapította — 'demi-gros' (fél-nagykereskedelmi). Ma a legnagyobb CH-i munkáltató.",
  },
  {
    id: "lang-fruehstueck",
    category: "language",
    question: "Mit jelent 'Frühstück'?",
    options: ["Vacsora", "Reggeli", "Ebéd", "Uzsonna"],
    correct: 1,
    explanation: "Reggeli. A 'Zmorge' a svájci-német megfelelője.",
  },
  {
    id: "lang-merci",
    category: "language",
    question: "Hogyan köszönsz meg a németajkú Svájcban informálisan?",
    options: ["'Danke'", "'Vielen Dank'", "'Merci' (francia eredetű)", "'Gracias'"],
    correct: 2,
    explanation: "A 'Merci' (vagy 'Merci vielmal') a leggyakoribb informális köszönet — a francia hatás miatt.",
  },

  // === ÉTEL +6 ===
  {
    id: "food-zopf",
    category: "food",
    question: "Mi a 'Zopf'?",
    options: [
      "Fonott vasárnapi kalács (vajas)",
      "Erős sajt",
      "Tészta-féle",
      "Söröskorsó",
    ],
    correct: 0,
    explanation: "Hagyományos fonott kalács — vasárnaponként reggelire. Erjesztett tejjel készül.",
  },
  {
    id: "food-buendnerfleisch",
    category: "food",
    question: "Mi a 'Bündnerfleisch'?",
    options: [
      "Sajt Graubündenből",
      "Szárított, fűszerezett marhahús szeletekben (graubündeni specialitás)",
      "Levesétel",
      "Disznó-szalonna",
    ],
    correct: 1,
    explanation: "Vékony, papírvékonyra vágott szárított marhahús. Klasszikus aperitif-falatka.",
  },
  {
    id: "food-aelpler",
    category: "food",
    question: "Mi az 'Älplermagronen'?",
    options: [
      "Egy bortí, alpesi régiókról",
      "Alpesi makaróni: tészta + krumpli + sajt + hagyma, almaszósszal",
      "Karaktermesés népdal",
      "Sajt-fagylalt",
    ],
    correct: 1,
    explanation: "Alpesi pásztor-étel — komfort-food. Tészta, krumpli, tejszín, hagyma, sajt — almaszósszal tálalva.",
  },
  {
    id: "food-bircher",
    category: "food",
    question: "Honnan ered a Bircher müzli?",
    options: [
      "Az Egyesült Államokból",
      "Svájcból — Dr. Maximilian Bircher-Brenner találmánya",
      "Németországból",
      "Norvégiából",
    ],
    correct: 1,
    explanation: "Dr. Bircher-Brenner zürichi orvos találta ki 1900 körül kórházi betegei számára egészséges reggelinek.",
  },
  {
    id: "food-lindt",
    category: "food",
    question: "Melyik svájci város szülöttje a Lindt csoki?",
    options: ["Genf", "Zürich", "Bern", "Lausanne"],
    correct: 1,
    explanation: "Lindt & Sprüngli — zürichi alapítású 1845-ben. A 'conching' (csoki-finomítás) feltalálója.",
  },
  {
    id: "food-kirsch",
    category: "food",
    question: "Mi a 'Kirsch'?",
    options: ["Cseresznyés sütemény", "Meggypálinka (cseresznyepárlat)", "Sajt-szósz", "Fűszer-keverék"],
    correct: 1,
    explanation: "Cseresznyepárlat — Zug és Schwyz kantonokban hagyományos. Fondue-ba is teszik egy kupica-nyit.",
  },

  // === KÖZLEKEDÉS +5 ===
  {
    id: "trans-vignette",
    category: "transport",
    question: "Mi a 'Vignette'?",
    options: [
      "Egy típusú vasúti jegy",
      "Autópálya-matrica — 40 CHF/év, kötelező autópályán",
      "Üdülő-helyi belépő",
      "Kantoni adóigazolás",
    ],
    correct: 1,
    explanation: "40 CHF/év (2024) — minden autópályán használt autón kell. Külön kell venni utánfutóra is.",
  },
  {
    id: "trans-glacier",
    category: "transport",
    question: "Mi a 'Glacier Express'?",
    options: [
      "A leggyorsabb svájci vonat",
      "Panoráma-vonat St. Moritz és Zermatt között (8 óra, gleccserek)",
      "Hegyi gyalogtúra",
      "Síliftes pálya",
    ],
    correct: 1,
    explanation: "Híres panoráma-vonat — 291 km, 7-8 óra, panoráma-kocsikkal. A 'lassú expressz'.",
  },
  {
    id: "trans-tram",
    category: "transport",
    question: "Melyik svájci városban NEM jár villamos (Tram)?",
    options: ["Zürich", "Bern", "Basel", "Luzern"],
    correct: 3,
    explanation: "Luzern-ben nincs villamos — csak troli (Trolleybus) és busz. A klasszikus villamos-városok: Zürich, Bern, Basel, Genf.",
  },
  {
    id: "trans-sbb-punctuality",
    category: "transport",
    question: "Mennyire pontos átlagosan az SBB?",
    options: ["75%", "85%", "92%+", "99%"],
    correct: 2,
    explanation: "Kb. 92%-os pontosság (a vonatok max 3 perc késéssel érkeznek). A világ egyik legpontosabb vasútrendszere.",
  },
  {
    id: "trans-cogwheel",
    category: "transport",
    question: "Mi a Pilatus-Bahn érdekessége?",
    options: [
      "Európa legrégibb fogaskerekű vasútja",
      "A világ legmeredekebb fogaskerekű vasútja (48% lejtő)",
      "Az egyetlen víz alatti vasút",
      "A leghosszabb földalatti vasút",
    ],
    correct: 1,
    explanation: "A világ legmeredekebb fogaskerekű vasútja (48% lejtő, 1889 óta) — a Pilatusra megy Luzern mellett.",
  },

  // === INTÉZMÉNYEK +6 ===
  {
    id: "inst-cern",
    category: "institutions",
    question: "Hol van a CERN székhelye?",
    options: ["Bern", "Genf", "Zürich", "Lugano"],
    correct: 1,
    explanation: "Genf — pontosabban a CH-FR határon. A CERN (Európai Nukleáris Kutatóközpont) 1954 óta működik.",
  },
  {
    id: "inst-snb",
    category: "institutions",
    question: "Mi az SNB?",
    options: [
      "Svájci nemzeti bank (Schweizerische Nationalbank)",
      "Egészségbiztosító",
      "Pénzügyminisztérium",
      "Magán-bank",
    ],
    correct: 0,
    explanation: "A svájci nemzeti bank — Bern és Zürich a két székhelye. Ő dönt a CHF kamatáról.",
  },
  {
    id: "inst-who",
    category: "institutions",
    question: "Hol van a WHO (Egészségügyi Világszervezet) székhelye?",
    options: ["New York", "Brüsszel", "Genf", "Washington"],
    correct: 2,
    explanation: "Genf — a klasszikus 'nemzetközi szervezetek városa'. WHO, ENSZ-iroda, ILO, ITU, ICRC mind itt.",
  },
  {
    id: "inst-migros-co-op",
    category: "institutions",
    question: "Milyen tulajdonosi formája van a Migrosnak?",
    options: [
      "Tőzsdén jegyzett részvénytársaság",
      "Szövetkezet (Genossenschaft) — a vásárlók a tulajdonosok",
      "Családi vállalkozás",
      "Állami tulajdonú",
    ],
    correct: 1,
    explanation: "Genossenschaft — kb. 2 millió szövetkezeti tag (vásárlók). Duttweiler-i öröksége. NEM árul alkoholt és cigarettát.",
  },
  {
    id: "inst-iv",
    category: "institutions",
    question: "Mi az 'IV'?",
    options: [
      "Időskori jövedelem",
      "Invaliditás-biztosítás (Invalidenversicherung) — rokkantsági nyugdíj",
      "Iskolai voucher",
      "Idegenforgalmi vám",
    ],
    correct: 1,
    explanation: "Invalidenversicherung — a rokkantsági biztosítás, az AHV-vel együtt az 1. piller.",
  },
  {
    id: "inst-pillars",
    category: "institutions",
    question: "Hány 'piller' van a svájci nyugdíj-rendszerben?",
    options: ["2", "3", "4", "5"],
    correct: 1,
    explanation: "3 piller: 1) állami (AHV), 2) kötelező foglalkozási (BVG), 3) magán (3a/3b). 'Drei-Säulen-System'.",
  },

  // === HÉTKÖZNAPOK +6 ===
  {
    id: "ev-twint",
    category: "everyday",
    question: "Mi a 'Twint'?",
    options: [
      "Svájci közlekedési app",
      "Svájci mobil-fizetési app (P2P + boltok + automaták)",
      "Időjárás-app",
      "Üzenetküldő app",
    ],
    correct: 1,
    explanation: "A svájci 'Revolut/PayPal' — bankok közös fejlesztése. Boltban QR-kóddal, ismerősnek telefonszámra.",
  },
  {
    id: "ev-work-hours",
    category: "everyday",
    question: "Mi a maximum törvényes heti munkaidő irodai munkára?",
    options: ["40 óra", "42 óra", "45 óra", "50 óra"],
    correct: 2,
    explanation: "45 óra/hét (kereskedelem, iroda). Egyéb szektorokban 50 óra. A gyakorlatban legtöbb cég 40-42 órát ad.",
  },
  {
    id: "ev-min-wage",
    category: "everyday",
    question: "Van-e szövetségi minimálbér Svájcban?",
    options: [
      "Igen, 4 000 CHF/hó",
      "Igen, 23 CHF/óra",
      "Nincs — csak kantoni szinten (Genf, Tessin, Neuchâtel)",
      "Igen, ágazatonként",
    ],
    correct: 2,
    explanation: "NINCS szövetségi minimálbér. Csak Genf (24 CHF/óra), Tessin, Neuchâtel, Jura, Basel-Stadt vezette be.",
  },
  {
    id: "ev-rent-deposit",
    category: "everyday",
    question: "Mennyi a tipikus lakás-óvadék (Mietkaution)?",
    options: ["1 havi bér", "2 havi bér", "3 havi bér (kötött bankszámlán)", "6 havi bér"],
    correct: 2,
    explanation: "Maximum 3 havi nettó bér — kötött bankszámlán (Kautionskonto), a bérlő nevére. Visszaadáskor kiengedik.",
  },
  {
    id: "ev-paying-bills",
    category: "everyday",
    question: "Mi a 'QR-Rechnung'?",
    options: [
      "Adóbevallás-mód",
      "Új svájci számla-formátum 2022-től (QR-kód automata befizetéshez)",
      "Sportverseny-naptár",
      "Postai csomag-követés",
    ],
    correct: 1,
    explanation: "2022-től a régi 'rózsaszín csekk' helyett QR-kódos számla. E-banking app szkenneli, automatikusan kitölti.",
  },
  {
    id: "ev-tip",
    category: "everyday",
    question: "Hogyan szokás borravalót adni étteremben?",
    options: [
      "Kötelező 15-20% mint az USA-ban",
      "Nem kötelező — szokás felkerekíteni vagy 5-10%-ot adni",
      "Sosem szokás",
      "Csak hitelkártya-fizetésnél",
    ],
    correct: 1,
    explanation: "A szolgáltatás (Service) már benne van az árban. Szokás kerekíteni felfelé, vagy 5-10% borravalót adni — de nem kötelező.",
  },
];

export function getQuestion(id: string): QuizQuestion | null {
  return QUIZ_BANK.find((q) => q.id === id) ?? null;
}
