-- db/seed-iranytu.sql — magyar ÉTTERMEK/BOLTOK DE (iranytunemetorszagban.de kurált lista).
-- Pontos cím = fő elérhetőség (helyhez kötött). Telefon/weboldal az OSM-extratagból, ha van.

INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-majsai-etterem-magyar-bufe','Majsai Étterem – Magyar Büfé','etterem','Étterem','Hopfenweg 41, 86381 Krumbach',NULL,'Magyar étterem','["Magyar"]',48.2514617,10.353087,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-gulasch-ungarisches-restaurant-und-weinkeller','Gulasch Ungarisches Restaurant und Weinkeller','etterem','Étterem','Hauptstraße 33, 86381 Krumbach',NULL,'Magyar étterem','["Magyar"]',48.2714527,10.3622308,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-pizzeria-rosenstuble','Pizzeria Rosenstüble','etterem','Étterem','Enzianstraße 1, 87459 Pfronten',NULL,'Magyar étterem','["Magyar"]',47.5663313,10.5669047,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-fleischmann-son-s-magyar-bolt','Fleischmann & Son''s Magyar Bolt','elelmiszer','Magyar bolt / élelmiszer','Heinrich-Wieland-Allee 2, 75177 Pforzheim',NULL,'Magyar magyar bolt / élelmiszer','["Magyar"]',48.8972878,8.7020098,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','BW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-ungarische-gourmet-kuche-gulyas-csarda','Ungarische Gourmet Küche – Gulyás Csárda','etterem','Étterem','Konradstraße 52, 63741 Aschaffenburg',NULL,'Magyar étterem','["Magyar"]',49.9984491,9.1148086,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-langos-express','Lángos Express','etterem','Étterem','Mainzer Straße 50, 64521 Groß-Gerau',NULL,'Magyar étterem','["Magyar"]',49.9224461,8.4729353,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','HE');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-moosachi-halaszcsarda','Moosachi Halászcsárda','etterem','Étterem','Dachauer Straße 457, 80993 München',NULL,'Magyar étterem','["Magyar"]',48.1831189,11.5069502,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-ildiko-csarda','Ildikó Csárda','etterem','Étterem','Thalhamer Straße 77, 84048 Mainburg',NULL,'Magyar étterem','["Magyar"]',48.6254287,11.8143596,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-terrasse-restaurant-dingelsdorf','Terrasse Restaurant Dingelsdorf','etterem','Étterem','Thingoltstraße 46, 78465 Konstanz','+49 152 539 535 33','Magyar étterem · www.terrasse-dingelsdorf.de','["Magyar"]',47.7355657,9.1547092,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','BW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-alte-bastei-restaurant','Alte Bastei Restaurant','etterem','Étterem','Hauptstraße 4, 74638 Waldenburg',NULL,'Magyar étterem','["Magyar"]',49.1902581,9.6423038,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','BW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-haus-munchshecke','Haus Münchshecke','etterem','Étterem','Hauptstraße 402, 53721 Siegburg',NULL,'Magyar étterem','["Magyar"]',50.7977074,7.2684102,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','NW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-rizoka-market','Rizoka Market','elelmiszer','Magyar bolt / élelmiszer','Altenessener Straße 305, 45326 Essen',NULL,'Magyar magyar bolt / élelmiszer','["Magyar"]',51.4897909,7.0087936,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','NW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-ungarische-lebensmittel-kaufbeuren','Ungarische Lebensmittel Kaufbeuren','elelmiszer','Magyar bolt / élelmiszer','Am Hofanger 22, 87600 Kaufbeuren',NULL,'Magyar magyar bolt / élelmiszer','["Magyar"]',47.8897496,10.6156767,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-ungarikum-papenburg','Ungarikum Papenburg','elelmiszer','Magyar bolt / élelmiszer','Tauschlägerstraße 15, 26871 Papenburg',NULL,'Magyar magyar bolt / élelmiszer','["Magyar"]',53.083869,7.436147,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','NI');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-betyar-markt','Betyár Markt','elelmiszer','Magyar bolt / élelmiszer','Altmühlstraße 17, 93309 Kelheim',NULL,'Magyar magyar bolt / élelmiszer','["Magyar"]',48.919802,11.8725942,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-budapest-ungarische-lebensmittel','Budapest Ungarische Lebensmittel','elelmiszer','Magyar bolt / élelmiszer','Bahnhofstraße 17, 79798 Jestetten',NULL,'Magyar magyar bolt / élelmiszer','["Magyar"]',47.6530162,8.5708273,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','BW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-ir-paprika-market-landshut','Paprika Market Landshut','elelmiszer','Magyar bolt / élelmiszer','Alte Regensburger Straße 60, 84030 Landshut',NULL,'Magyar magyar bolt / élelmiszer','["Magyar"]',48.5489442,12.1597066,50,50,0,0,0,0,1,0,0,0,'seed-iranytu','DE','BY');
