-- db/seed-nl.sql — AUTOGENERÁLT (scripts/gen-nl-seed.mjs). NE szerkeszd kézzel.
-- Valódi hollandiai magyar szervezetek. Alkalmazás a 0081 migráció UTÁN:
--   wrangler d1 execute kinti-db --remote --file=./db/seed-nl.sql

-- 1) Közösség-kategória (ország-független, OR IGNORE — a többi seed is ezt használja).
INSERT OR IGNORE INTO categories (id, label, glyph, sort_order) VALUES ('magyar-kozosseg', 'Magyar közösség / egyesület', '🇭🇺', 900);

-- 2) Szervezetek (country_code='NL', régió a canton_code-ban, jóváhagyva, nem foglalt).
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-amszterdami-hungaria-klub-1929', 'Amszterdami Hungária Klub 1929', 'magyar-kozosseg', 'Kulturális egyesület', 'Amsterdam', 'Magyar kulturális egyesület · Amsterdam · hungariaclub1929.nl', '["Magyar"]', 52.3676, 4.9041, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'NH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-amszterdami-magyar-ovoda-es-iskola', 'Amszterdami Magyar Óvoda és Iskola', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Amsterdam', 'Hétvégi magyar iskola · Amsterdam', '["Magyar"]', 52.3676, 4.9041, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'NH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-baba-mama-klub-amszterdam', 'Baba-Mama Klub Amszterdam', 'magyar-kozosseg', 'Baba-mama klub', 'Amsterdam', 'Magyar baba-mama klub · Amsterdam', '["Magyar"]', 52.3676, 4.9041, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'NH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-amstelveeni-magyar-ovoda-es-iskola', 'Amstelveeni Magyar Óvoda és Iskola', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Amstelveen', 'Hétvégi magyar iskola · Amstelveen · www.amstelveeni-magyariskola.nl', '["Magyar"]', 52.3114, 4.8701, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'NH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-kolcsey-ferenc-magyar-egyesulet', 'Kölcsey Ferenc Magyar Egyesület', 'magyar-kozosseg', 'Kulturális egyesület', 'Alkmaar', 'Magyar kulturális egyesület · Alkmaar', '["Magyar"]', 52.6324, 4.7534, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'NH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-hollandiai-magyar-szovetseg', 'Hollandiai Magyar Szövetség', 'magyar-kozosseg', 'Országos ernyőszervezet', 'Den Haag', 'Magyar országos ernyőszervezet · Den Haag · www.hongaarsefederatie.nl', '["Magyar"]', 52.0705, 4.3007, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'ZH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-hagai-magyar-ovoda-es-iskola', 'Hágai Magyar Óvoda és Iskola', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Den Haag', 'Hétvégi magyar iskola · Den Haag', '["Magyar"]', 52.0705, 4.3007, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'ZH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-hagai-magyar-reformatus-gyulekezet', 'Hágai Magyar Református Gyülekezet', 'magyar-kozosseg', 'Református gyülekezet', 'Den Haag', 'Magyar református gyülekezet · Den Haag', '["Magyar"]', 52.0705, 4.3007, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'ZH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-hollandiai-magyar-romai-katolikus-egyhazkozseg', 'Hollandiai Magyar Római Katolikus Egyházközség', 'magyar-kozosseg', 'Katolikus egyházközség', 'Den Haag', 'Magyar katolikus egyházközség · Den Haag', '["Magyar"]', 52.0705, 4.3007, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'ZH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-utrechti-magyar-klub', 'Utrechti Magyar Klub', 'magyar-kozosseg', 'Kulturális egyesület', 'Utrecht', 'Magyar kulturális egyesület · Utrecht', '["Magyar"]', 52.0907, 5.1214, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'UT');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-utrechti-magyar-iskola', 'Utrechti Magyar Iskola', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Utrecht', 'Hétvégi magyar iskola · Utrecht', '["Magyar"]', 52.0907, 5.1214, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'UT');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-maarsseni-kincskereso-iskola', 'Maarsseni Kincskereső Iskola', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Maarssen', 'Hétvégi magyar iskola · Maarssen · kincskereso-oskola.nl', '["Magyar"]', 52.1389, 5.0386, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'UT');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-vianeni-magyar-otthon', 'Vianeni Magyar Otthon', 'magyar-kozosseg', 'Közösségi ház', 'Vianen', 'Magyar közösségi ház · Vianen', '["Magyar"]', 51.9897, 5.0936, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'UT');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-eindhoveni-magyar-ovoda-suli', 'Eindhoveni Magyar Óvoda-Suli', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Eindhoven', 'Hétvégi magyar iskola · Eindhoven · eindhoveni-ovisuli.nl', '["Magyar"]', 51.4416, 5.4697, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'NB');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-hengeloi-magyar-iskola', 'Hengelói Magyar Iskola', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Hengelo', 'Hétvégi magyar iskola · Hengelo', '["Magyar"]', 52.2659, 6.793, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'OV');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-zwollei-magyar-reformatus-egyhazkozseg', 'Zwollei Magyar Református Egyházközség', 'magyar-kozosseg', 'Református gyülekezet', 'Zwolle', 'Magyar református gyülekezet · Zwolle · zwolleireformatus.nl', '["Magyar"]', 52.5168, 6.083, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'OV');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-meppeli-magyar-iskola', 'Meppeli Magyar Iskola', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Meppel', 'Hétvégi magyar iskola · Meppel', '["Magyar"]', 52.6957, 6.1939, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'DR');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('nl-limburgi-rakoczi-ferenc-magyar-klub', 'Limburgi Rákóczi Ferenc Magyar Klub', 'magyar-kozosseg', 'Kulturális egyesület', 'Maastricht', 'Magyar kulturális egyesület · Maastricht', '["Magyar"]', 50.8514, 5.691, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-nl-org', 'NL', 'LI');
