-- db/seed-gb.sql — AUTOGENERÁLT (scripts/gen-gb-seed.mjs). NE szerkeszd kézzel.
-- Valódi angliai magyar szervezetek, ellenőrzött elérhetőséggel. Alkalmazás:
--   wrangler d1 execute kinti-db --remote --file=./db/seed-gb.sql

-- 1) Közösség-kategória (ország-független, OR IGNORE — a többi seed is ezt használja).
INSERT OR IGNORE INTO categories (id, label, glyph, sort_order) VALUES ('magyar-kozosseg', 'Magyar közösség / egyesület', '🇭🇺', 900);

-- 2) Szervezetek (country_code='GB', régió a canton_code-ban, jóváhagyva, nem foglalt).
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-szent-istvan-haz-angliai-romai-katolikus-magyarok-egyesulete', 'Szent István Ház — Angliai Római Katolikus Magyarok Egyesülete (ARKME)', 'magyar-kozosseg', 'Katolikus közösségi ház', '62 Little Ealing Lane, London W5 4EA', NULL, 'hello@szentistvanhaz.org', 'Katolikus közösségi ház · London · szentistvanhaz.org', '["Magyar"]', 51.4973104, -0.3113869, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = '62 Little Ealing Lane, London W5 4EA', phone = NULL, contact_email = 'hello@szentistvanhaz.org', open_text = NULL, lat = 51.4973104, lng = -0.3113869, category_id = 'magyar-kozosseg', blurb = 'Katolikus közösségi ház · London · szentistvanhaz.org' WHERE id = 'gb-szent-istvan-haz-angliai-romai-katolikus-magyarok-egyesulete' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-angliai-magyar-reformatus-egyhaz', 'Angliai Magyar Református Egyház', 'magyar-kozosseg', 'Református gyülekezet', '17 St Dunstan''s Road, London W6 8RD', '+44 20 8748 8858', 'info@reflondon.hu', 'Református gyülekezet · London · reflondon.hu', '["Magyar"]', 51.48979, -0.21629, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = '17 St Dunstan''s Road, London W6 8RD', phone = '+44 20 8748 8858', contact_email = 'info@reflondon.hu', open_text = NULL, lat = 51.48979, lng = -0.21629, category_id = 'magyar-kozosseg', blurb = 'Református gyülekezet · London · reflondon.hu' WHERE id = 'gb-angliai-magyar-reformatus-egyhaz' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-magyar-kulturalis-kozpont-london', 'Magyar Kulturális Központ London', 'magyar-kozosseg', 'Kulturális központ', '10 Maiden Lane, Covent Garden, London WC2E 7NA', '+44 20 7257 2023', NULL, 'Kulturális központ · London · www.hungary.org.uk', '["Magyar"]', 51.5106708, -0.1228868, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = '10 Maiden Lane, Covent Garden, London WC2E 7NA', phone = '+44 20 7257 2023', contact_email = NULL, open_text = NULL, lat = 51.5106708, lng = -0.1228868, category_id = 'magyar-kozosseg', blurb = 'Kulturális központ · London · www.hungary.org.uk' WHERE id = 'gb-magyar-kulturalis-kozpont-london' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-magyarorszag-nagykovetsege-london', 'Magyarország Nagykövetsége — London', 'magyar-kozosseg', 'Nagykövetség', '35 Eaton Place, London SW1X 8BY', '+44 20 7201 3440', 'mission.lon@mfa.gov.hu', 'Nagykövetség · London · london.mfa.gov.hu', '["Magyar"]', 51.4972713, -0.1527801, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = '35 Eaton Place, London SW1X 8BY', phone = '+44 20 7201 3440', contact_email = 'mission.lon@mfa.gov.hu', open_text = NULL, lat = 51.4972713, lng = -0.1527801, category_id = 'magyar-kozosseg', blurb = 'Nagykövetség · London · london.mfa.gov.hu' WHERE id = 'gb-magyarorszag-nagykovetsege-london' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-magyarorszag-nagykovetsege-konzuli-osztaly', 'Magyarország Nagykövetsége — Konzuli Osztály', 'magyar-kozosseg', 'Konzuli osztály', '100 Brompton Road, London SW3 1ER', '+44 20 7235 5218', 'consulate.lon@mfa.gov.hu', 'Konzuli osztály · London · london.mfa.gov.hu', '["Magyar"]', 51.4994966, -0.1644538, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = '100 Brompton Road, London SW3 1ER', phone = '+44 20 7235 5218', contact_email = 'consulate.lon@mfa.gov.hu', open_text = NULL, lat = 51.4994966, lng = -0.1644538, category_id = 'magyar-kozosseg', blurb = 'Konzuli osztály · London · london.mfa.gov.hu' WHERE id = 'gb-magyarorszag-nagykovetsege-konzuli-osztaly' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-londoni-magyar-iskola', 'Londoni Magyar Iskola+', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'London', NULL, 'LMIplusz@gmail.com', 'Hétvégi magyar iskola · London · magyariskola.org.uk', '["Magyar"]', 51.5074, -0.1278, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = 'London', phone = NULL, contact_email = 'LMIplusz@gmail.com', open_text = NULL, lat = 51.5074, lng = -0.1278, category_id = 'magyar-kozosseg', blurb = 'Hétvégi magyar iskola · London · magyariskola.org.uk' WHERE id = 'gb-londoni-magyar-iskola' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-mosoly-magyar-ovi-suli', 'MOSOLY Magyar Ovi-Suli', 'magyar-kozosseg', 'Hétvégi magyar óvoda és iskola', 'London', '+44 7961 441041', 'info@magyarovisuli.co.uk', 'Hétvégi magyar óvoda és iskola · London · magyarovisuli.co.uk', '["Magyar"]', 51.5074, -0.1278, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = 'London', phone = '+44 7961 441041', contact_email = 'info@magyarovisuli.co.uk', open_text = NULL, lat = 51.5074, lng = -0.1278, category_id = 'magyar-kozosseg', blurb = 'Hétvégi magyar óvoda és iskola · London · magyarovisuli.co.uk' WHERE id = 'gb-mosoly-magyar-ovi-suli' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-maki-suli-london', 'MAKI Suli London', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'London', NULL, 'makisulilondon@gmail.com', 'Hétvégi magyar iskola · London · makisulilondon.wixsite.com/maki', '["Magyar"]', 51.5074, -0.1278, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = 'London', phone = NULL, contact_email = 'makisulilondon@gmail.com', open_text = NULL, lat = 51.5074, lng = -0.1278, category_id = 'magyar-kozosseg', blurb = 'Hétvégi magyar iskola · London · makisulilondon.wixsite.com/maki' WHERE id = 'gb-maki-suli-london' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-birminghami-magyar-tanoda-es-kulturalis-kozpont', 'Birminghami Magyar Tanoda és Kulturális Központ', 'magyar-kozosseg', 'Hétvégi magyar iskola és kulturális központ', 'Selly Oak Methodist Church, Langleys Road, Birmingham B29 6HT', '+44 7756 214875', 'birminghamiskola@gmail.com', 'Hétvégi magyar iskola és kulturális központ · Birmingham · birminghamimagyarok.org', '["Magyar"]', 52.4345424, -1.9407083, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'WM');
UPDATE businesses SET address = 'Selly Oak Methodist Church, Langleys Road, Birmingham B29 6HT', phone = '+44 7756 214875', contact_email = 'birminghamiskola@gmail.com', open_text = NULL, lat = 52.4345424, lng = -1.9407083, category_id = 'magyar-kozosseg', blurb = 'Hétvégi magyar iskola és kulturális központ · Birmingham · birminghamimagyarok.org' WHERE id = 'gb-birminghami-magyar-tanoda-es-kulturalis-kozpont' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-coventry-magyar-tanoda-es-kozosseg', 'Coventry Magyar Tanoda és Közösség', 'magyar-kozosseg', 'Hétvégi magyar iskola és közösség', 'Coventry', NULL, 'coventrymagyartanoda@gmail.com', 'Hétvégi magyar iskola és közösség · Coventry · comat.org.uk', '["Magyar"]', 52.4068, -1.5197, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'WM');
UPDATE businesses SET address = 'Coventry', phone = NULL, contact_email = 'coventrymagyartanoda@gmail.com', open_text = NULL, lat = 52.4068, lng = -1.5197, category_id = 'magyar-kozosseg', blurb = 'Hétvégi magyar iskola és közösség · Coventry · comat.org.uk' WHERE id = 'gb-coventry-magyar-tanoda-es-kozosseg' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-zsigmond-kiraly-magyar-kulturalis-klub-es-iskola', 'Zsigmond Király Magyar Kulturális Klub és Iskola', 'magyar-kozosseg', 'Magyar kulturális klub és hétvégi iskola', 'Manchester', NULL, 'zsk.iskola@gmail.com', 'Magyar kulturális klub és hétvégi iskola · Manchester · zsigmondkiraly.co.uk', '["Magyar"]', 53.4808, -2.2426, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'NW');
UPDATE businesses SET address = 'Manchester', phone = NULL, contact_email = 'zsk.iskola@gmail.com', open_text = NULL, lat = 53.4808, lng = -2.2426, category_id = 'magyar-kozosseg', blurb = 'Magyar kulturális klub és hétvégi iskola · Manchester · zsigmondkiraly.co.uk' WHERE id = 'gb-zsigmond-kiraly-magyar-kulturalis-klub-es-iskola' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-magyar-iskola-cambridge', 'Magyar Iskola Cambridge', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Cambridge', NULL, 'magyariskolacambridge@gmail.com', 'Hétvégi magyar iskola · Cambridge', '["Magyar"]', 52.2053, 0.1218, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'EE');
UPDATE businesses SET address = 'Cambridge', phone = NULL, contact_email = 'magyariskolacambridge@gmail.com', open_text = NULL, lat = 52.2053, lng = 0.1218, category_id = 'magyar-kozosseg', blurb = 'Hétvégi magyar iskola · Cambridge' WHERE id = 'gb-magyar-iskola-cambridge' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-st-albans-i-magyar-iskola', 'St Albans-i Magyar Iskola', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'St Albans', NULL, 'hungarianschoolofstalbans@gmail.com', 'Hétvégi magyar iskola · St Albans · www.hungarianschool.co.uk', '["Magyar"]', 51.752, -0.3369, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'EE');
UPDATE businesses SET address = 'St Albans', phone = NULL, contact_email = 'hungarianschoolofstalbans@gmail.com', open_text = NULL, lat = 51.752, lng = -0.3369, category_id = 'magyar-kozosseg', blurb = 'Hétvégi magyar iskola · St Albans · www.hungarianschool.co.uk' WHERE id = 'gb-st-albans-i-magyar-iskola' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-guildfordi-magyar-tanoda-es-jatszohaz', 'Guildfordi Magyar Tanoda és Játszóház', 'magyar-kozosseg', 'Hétvégi magyar iskola és játszóház', 'Guildford', '+44 1483 808643', 'info@hcaguildford.org.uk', 'Hétvégi magyar iskola és játszóház · Guildford · hcaguildford.org.uk', '["Magyar"]', 51.2362, -0.5704, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'SE');
UPDATE businesses SET address = 'Guildford', phone = '+44 1483 808643', contact_email = 'info@hcaguildford.org.uk', open_text = NULL, lat = 51.2362, lng = -0.5704, category_id = 'magyar-kozosseg', blurb = 'Hétvégi magyar iskola és játszóház · Guildford · hcaguildford.org.uk' WHERE id = 'gb-guildfordi-magyar-tanoda-es-jatszohaz' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-readingi-magyar-iskola', 'Readingi Magyar Iskola', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Reading', '+44 7533 337720', 'readingi.magyar.iskola@gmail.com', 'Hétvégi magyar iskola · Reading', '["Magyar"]', 51.4543, -0.9781, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'SE');
UPDATE businesses SET address = 'Reading', phone = '+44 7533 337720', contact_email = 'readingi.magyar.iskola@gmail.com', open_text = NULL, lat = 51.4543, lng = -0.9781, category_id = 'magyar-kozosseg', blurb = 'Hétvégi magyar iskola · Reading' WHERE id = 'gb-readingi-magyar-iskola' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-magyar-iskola-woking', 'Magyar Iskola Woking', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Woking', NULL, 'info@magyariskolawoking.org.uk', 'Hétvégi magyar iskola · Woking · magyariskolawoking.org.uk', '["Magyar"]', 51.3168, -0.561, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'SE');
UPDATE businesses SET address = 'Woking', phone = NULL, contact_email = 'info@magyariskolawoking.org.uk', open_text = NULL, lat = 51.3168, lng = -0.561, category_id = 'magyar-kozosseg', blurb = 'Hétvégi magyar iskola · Woking · magyariskolawoking.org.uk' WHERE id = 'gb-magyar-iskola-woking' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-magyar-iskola-oxford', 'Magyar Iskola Oxford', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Oxford', NULL, 'hunschoolox@gmail.com', 'Hétvégi magyar iskola · Oxford', '["Magyar"]', 51.752, -1.2577, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'SE');
UPDATE businesses SET address = 'Oxford', phone = NULL, contact_email = 'hunschoolox@gmail.com', open_text = NULL, lat = 51.752, lng = -1.2577, category_id = 'magyar-kozosseg', blurb = 'Hétvégi magyar iskola · Oxford' WHERE id = 'gb-magyar-iskola-oxford' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-basingstoke-i-magyar-ovi-es-suli', 'Basingstoke-i Magyar Ovi és Suli', 'magyar-kozosseg', 'Hétvégi magyar óvoda és iskola', 'Basingstoke', '+44 7766 951790', 'basingstoke@magyar.org.uk', 'Hétvégi magyar óvoda és iskola · Basingstoke', '["Magyar"]', 51.2665, -1.0873, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'SE');
UPDATE businesses SET address = 'Basingstoke', phone = '+44 7766 951790', contact_email = 'basingstoke@magyar.org.uk', open_text = NULL, lat = 51.2665, lng = -1.0873, category_id = 'magyar-kozosseg', blurb = 'Hétvégi magyar óvoda és iskola · Basingstoke' WHERE id = 'gb-basingstoke-i-magyar-ovi-es-suli' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-southamptoni-magyar-iskola', 'Southamptoni Magyar Iskola', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Southampton', NULL, 'hello@southamptonimagyariskola.org.uk', 'Hétvégi magyar iskola · Southampton · southamptonimagyariskola.org.uk', '["Magyar"]', 50.9097, -1.4044, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'SE');
UPDATE businesses SET address = 'Southampton', phone = NULL, contact_email = 'hello@southamptonimagyariskola.org.uk', open_text = NULL, lat = 50.9097, lng = -1.4044, category_id = 'magyar-kozosseg', blurb = 'Hétvégi magyar iskola · Southampton · southamptonimagyariskola.org.uk' WHERE id = 'gb-southamptoni-magyar-iskola' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-bristoli-magyar-kisiskola', 'Bristoli Magyar Kisiskola', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Bristol', NULL, NULL, 'Hétvégi magyar iskola · Bristol · bristolikisiskola.org', '["Magyar"]', 51.4545, -2.5879, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'SW');
UPDATE businesses SET address = 'Bristol', phone = NULL, contact_email = NULL, open_text = NULL, lat = 51.4545, lng = -2.5879, category_id = 'magyar-kozosseg', blurb = 'Hétvégi magyar iskola · Bristol · bristolikisiskola.org' WHERE id = 'gb-bristoli-magyar-kisiskola' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-magyar-izek-hungarian-flavors-ltd', 'Magyar Ízek — Hungarian Flavors Ltd', 'elelmiszer', 'Magyar élelmiszerbolt', '660 High Road, North Finchley, London N12 0NL', '+44 20 8446 2793', NULL, 'Magyar élelmiszerbolt · London · www.facebook.com/HUNFLAV', '["Magyar"]', 51.6120246, -0.1754892, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = '660 High Road, North Finchley, London N12 0NL', phone = '+44 20 8446 2793', contact_email = NULL, open_text = NULL, lat = 51.6120246, lng = -0.1754892, category_id = 'elelmiszer', blurb = 'Magyar élelmiszerbolt · London · www.facebook.com/HUNFLAV' WHERE id = 'gb-magyar-izek-hungarian-flavors-ltd' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-magyarok-boltja-wimbledon', 'Magyarok Boltja Wimbledon', 'elelmiszer', 'Magyar élelmiszerbolt', '177 Kingston Road, Wimbledon, London SW19 1LH', '+44 20 8540 1119', NULL, 'Magyar élelmiszerbolt · London · hungariandeli.co.uk', '["Magyar"]', 51.4146026, -0.2016084, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = '177 Kingston Road, Wimbledon, London SW19 1LH', phone = '+44 20 8540 1119', contact_email = NULL, open_text = NULL, lat = 51.4146026, lng = -0.2016084, category_id = 'elelmiszer', blurb = 'Magyar élelmiszerbolt · London · hungariandeli.co.uk' WHERE id = 'gb-magyarok-boltja-wimbledon' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-taste-from-hungary-magyar-bolt', 'Taste From Hungary Magyar Bolt', 'elelmiszer', 'Magyar élelmiszerbolt', '50 Chesterton Road, Cambridge CB4 1EN', NULL, NULL, 'Magyar élelmiszerbolt · Cambridge', '["Magyar"]', 52.214405, 0.1266061, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'EE');
UPDATE businesses SET address = '50 Chesterton Road, Cambridge CB4 1EN', phone = NULL, contact_email = NULL, open_text = NULL, lat = 52.214405, lng = 0.1266061, category_id = 'elelmiszer', blurb = 'Magyar élelmiszerbolt · Cambridge' WHERE id = 'gb-taste-from-hungary-magyar-bolt' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-pick-your-taste-magyar-bolt-paprika-store', 'Pick Your Taste Magyar Bolt / Paprika Store', 'elelmiszer', 'Magyar élelmiszerbolt', '72 Queensway, Bletchley, Milton Keynes MK2 2SA', '+44 7429 499115', NULL, 'Magyar élelmiszerbolt · Milton Keynes', '["Magyar"]', 51.9944976, -0.7319751, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'SE');
UPDATE businesses SET address = '72 Queensway, Bletchley, Milton Keynes MK2 2SA', phone = '+44 7429 499115', contact_email = NULL, open_text = NULL, lat = 51.9944976, lng = -0.7319751, category_id = 'elelmiszer', blurb = 'Magyar élelmiszerbolt · Milton Keynes' WHERE id = 'gb-pick-your-taste-magyar-bolt-paprika-store' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-taste-from-europe-angliai-magyar-bolt', 'Taste From Europe — Angliai Magyar Bolt', 'elelmiszer', 'Magyar élelmiszer webshop és bolt', '35 Field End, Witchford, Cambridgeshire CB6 2XE', '+44 7951 923337', NULL, 'Magyar élelmiszer webshop és bolt · Witchford · store75949285.company.site', '["Magyar"]', 52.3888329, 0.1994636, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'EE');
UPDATE businesses SET address = '35 Field End, Witchford, Cambridgeshire CB6 2XE', phone = '+44 7951 923337', contact_email = NULL, open_text = NULL, lat = 52.3888329, lng = 0.1994636, category_id = 'elelmiszer', blurb = 'Magyar élelmiszer webshop és bolt · Witchford · store75949285.company.site' WHERE id = 'gb-taste-from-europe-angliai-magyar-bolt' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-lakehouse-hungarian-restaurant', 'Lakehouse Hungarian Restaurant', 'etterem', 'Magyar étterem', '83 High Road, South Woodford, London E18 2QP', '+44 7711 585380', '324lakehouse@gmail.com', 'Magyar étterem · London · www.lakehouserestaurant.co.uk', '["Magyar"]', 51.5945276, 0.0221148, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = '83 High Road, South Woodford, London E18 2QP', phone = '+44 7711 585380', contact_email = '324lakehouse@gmail.com', open_text = NULL, lat = 51.5945276, lng = 0.0221148, category_id = 'etterem', blurb = 'Magyar étterem · London · www.lakehouserestaurant.co.uk' WHERE id = 'gb-lakehouse-hungarian-restaurant' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-turul-project-magyar-etterem-es-borbar', 'Turul Project — magyar étterem és borbár', 'etterem', 'Magyar étterem, borbár és delikát', '1 Turnpike Parade, London N15 3LA', '+44 20 8888 9886', NULL, 'Magyar étterem, borbár és delikát · London · www.turulproject.com', '["Magyar"]', 51.5074, -0.1278, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = '1 Turnpike Parade, London N15 3LA', phone = '+44 20 8888 9886', contact_email = NULL, open_text = NULL, lat = 51.5074, lng = -0.1278, category_id = 'etterem', blurb = 'Magyar étterem, borbár és delikát · London · www.turulproject.com' WHERE id = 'gb-turul-project-magyar-etterem-es-borbar' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-paprika-store-london-green-lanes', 'Paprika Store London — Green Lanes', 'elelmiszer', 'Magyar élelmiszerbolt', '50 Grand Parade, Green Lanes, Haringey, London N4 1AG', '+44 20 3645 9092', 'london@paprikastore.co.uk', 'Magyar élelmiszerbolt · London · www.paprikastore.co.uk', '["Magyar"]', 51.5790634, -0.0988797, 50, 50, 0, 0, 0, 0, 'H–P 10–19, Szo 9–19, V és bank holiday 10–19', 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = '50 Grand Parade, Green Lanes, Haringey, London N4 1AG', phone = '+44 20 3645 9092', contact_email = 'london@paprikastore.co.uk', open_text = 'H–P 10–19, Szo 9–19, V és bank holiday 10–19', lat = 51.5790634, lng = -0.0988797, category_id = 'elelmiszer', blurb = 'Magyar élelmiszerbolt · London · www.paprikastore.co.uk' WHERE id = 'gb-paprika-store-london-green-lanes' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-paprika-store-twickenham', 'Paprika Store Twickenham', 'elelmiszer', 'Magyar élelmiszerbolt', '40B Heath Road, Twickenham TW1 4BZ', '+44 20 7998 7608', 'twickenham@paprikastore.co.uk', 'Magyar élelmiszerbolt · Twickenham · www.paprikastore.co.uk', '["Magyar"]', 51.4454274, -0.3317172, 50, 50, 0, 0, 0, 0, 'H–P 10–19, V és bank holiday 10–16', 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = '40B Heath Road, Twickenham TW1 4BZ', phone = '+44 20 7998 7608', contact_email = 'twickenham@paprikastore.co.uk', open_text = 'H–P 10–19, V és bank holiday 10–16', lat = 51.4454274, lng = -0.3317172, category_id = 'elelmiszer', blurb = 'Magyar élelmiszerbolt · Twickenham · www.paprikastore.co.uk' WHERE id = 'gb-paprika-store-twickenham' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-paprika-store-bristol', 'Paprika Store Bristol', 'elelmiszer', 'Magyar élelmiszerbolt', '47 Old Market Street, Bristol BS2 0EX', '+44 117 329 1370', 'bristol@paprikastore.co.uk', 'Magyar élelmiszerbolt · Bristol · www.paprikastore.co.uk', '["Magyar"]', 51.4565176, -2.5804175, 50, 50, 0, 0, 0, 0, 'H–Szo 10–19, V és bank holiday 10–16', 1, 0, 0, 'seed-gb-org', 'GB', 'SW');
UPDATE businesses SET address = '47 Old Market Street, Bristol BS2 0EX', phone = '+44 117 329 1370', contact_email = 'bristol@paprikastore.co.uk', open_text = 'H–Szo 10–19, V és bank holiday 10–16', lat = 51.4565176, lng = -2.5804175, category_id = 'elelmiszer', blurb = 'Magyar élelmiszerbolt · Bristol · www.paprikastore.co.uk' WHERE id = 'gb-paprika-store-bristol' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-paprika-store-nottingham', 'Paprika Store Nottingham', 'elelmiszer', 'Magyar élelmiszerbolt', '1 The City, Beeston, Nottingham NG9 2ED', '+44 115 837 0080', 'nottingham@paprikastore.co.uk', 'Magyar élelmiszerbolt · Nottingham · www.paprikastore.co.uk', '["Magyar"]', 52.9272746, -1.2098735, 50, 50, 0, 0, 0, 0, 'H–Szo 10–19, V és bank holiday 10–16', 1, 0, 0, 'seed-gb-org', 'GB', 'EM');
UPDATE businesses SET address = '1 The City, Beeston, Nottingham NG9 2ED', phone = '+44 115 837 0080', contact_email = 'nottingham@paprikastore.co.uk', open_text = 'H–Szo 10–19, V és bank holiday 10–16', lat = 52.9272746, lng = -1.2098735, category_id = 'elelmiszer', blurb = 'Magyar élelmiszerbolt · Nottingham · www.paprikastore.co.uk' WHERE id = 'gb-paprika-store-nottingham' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-hungarian-market-birmingham', 'Hungarian Market Birmingham', 'elelmiszer', 'Magyar élelmiszerbolt', '184 Sutton New Road, Erdington, Birmingham B23 6QU', '+44 7564 226951', 'hungarianmarket012@gmail.com', 'Magyar élelmiszerbolt · Birmingham · hungarianmarket.co.uk', '["Magyar"]', 52.5263302, -1.8378371, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'WM');
UPDATE businesses SET address = '184 Sutton New Road, Erdington, Birmingham B23 6QU', phone = '+44 7564 226951', contact_email = 'hungarianmarket012@gmail.com', open_text = NULL, lat = 52.5263302, lng = -1.8378371, category_id = 'elelmiszer', blurb = 'Magyar élelmiszerbolt · Birmingham · hungarianmarket.co.uk' WHERE id = 'gb-hungarian-market-birmingham' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-louis-hungarian-patisserie', 'Louis Hungarian Patisserie', 'cukrasz', 'Magyar cukrászda (1963 óta)', '32 Heath Street, Hampstead, London NW3 6TE', '+44 20 7435 9908', NULL, 'Magyar cukrászda (1963 óta) · London', '["Magyar"]', 51.5556728, -0.1786265, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = '32 Heath Street, Hampstead, London NW3 6TE', phone = '+44 20 7435 9908', contact_email = NULL, open_text = NULL, lat = 51.5556728, lng = -0.1786265, category_id = 'cukrasz', blurb = 'Magyar cukrászda (1963 óta) · London' WHERE id = 'gb-louis-hungarian-patisserie' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-chimney-cake-lady-kurtoskalacs', 'Chimney Cake Lady — kürtőskalács', 'cukrasz', 'Kürtőskalács-pult a Camden Marketen', 'Waterside Halls, Camden Market Hawley Wharf, London NW1 8QH', NULL, NULL, 'Kürtőskalács-pult a Camden Marketen · London · www.instagram.com/chimneycakelady', '["Magyar"]', 51.5422296, -0.1442459, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = 'Waterside Halls, Camden Market Hawley Wharf, London NW1 8QH', phone = NULL, contact_email = NULL, open_text = NULL, lat = 51.5422296, lng = -0.1442459, category_id = 'cukrasz', blurb = 'Kürtőskalács-pult a Camden Marketen · London · www.instagram.com/chimneycakelady' WHERE id = 'gb-chimney-cake-lady-kurtoskalacs' AND claimed = 0 AND source = 'seed-gb-org';
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, open_text, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-strike-consulting-london-ltd-magyar-konyveloiroda', 'Strike Consulting (London) Ltd — magyar könyvelőiroda', 'konyveles', 'Magyar könyvelőiroda (self-employed, Ltd, cégalapítás)', '44 Broadway, Stratford, London E15 1XH', '+44 20 3987 4684', 'tax@akonyvelo.co.uk', 'Magyar könyvelőiroda (self-employed, Ltd, cégalapítás) · London · akonyvelo.co.uk', '["Magyar"]', 51.5410349, 0.0007492, 50, 50, 0, 0, 0, 0, NULL, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
UPDATE businesses SET address = '44 Broadway, Stratford, London E15 1XH', phone = '+44 20 3987 4684', contact_email = 'tax@akonyvelo.co.uk', open_text = NULL, lat = 51.5410349, lng = 0.0007492, category_id = 'konyveles', blurb = 'Magyar könyvelőiroda (self-employed, Ltd, cégalapítás) · London · akonyvelo.co.uk' WHERE id = 'gb-strike-consulting-london-ltd-magyar-konyveloiroda' AND claimed = 0 AND source = 'seed-gb-org';
