-- db/seed-at.sql — AUTOGENERÁLT (scripts/gen-at-seed.mjs). NE szerkeszd kézzel.
-- Valódi osztrák magyar szervezetek. Alkalmazás a 0081 migráció UTÁN:
--   wrangler d1 execute kinti-db --remote --file=./db/seed-at.sql

-- 1) Közösség-kategória (ország-független, de csak AT-ben lesz rá tartalom).
INSERT OR IGNORE INTO categories (id, label, glyph, sort_order) VALUES ('magyar-kozosseg', 'Magyar közösség / egyesület', '🇭🇺', 900);

-- 2) Szervezetek (country_code='AT', régió a canton_code-ban, jóváhagyva, nem foglalt).
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-ausztriai-magyar-evangelikus-gyulekezet', 'Ausztriai Magyar Evangélikus Gyülekezet', 'magyar-kozosseg', 'Egyház', 'Wien', 'Magyar egyház · Wien · evangelikus-at.com', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-ausztriai-magyar-diakok-egyesulete', 'Ausztriai Magyar Diákok Egyesülete', 'magyar-kozosseg', 'Diákszervezet', 'Wien', 'Magyar diákszervezet · Wien', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-ausztriai-magyar-kutatointezet', 'Ausztriai Magyar Kutatóintézet', 'magyar-kozosseg', 'Kutatóintézet', 'Wien', 'Magyar kutatóintézet · Wien · oeius.univie.ac.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-amaped-ausztriai-magyar-pedagogusok-egyesulete', 'AMAPED – Ausztriai Magyar Pedagógusok Egyesülete', 'magyar-kozosseg', 'Oktatás', 'Wien', 'Magyar oktatás · Wien · amaped.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-ausztriai-magyar-reformatus-lelkigondozo-szolgalat', 'Ausztriai Magyar Református Lelkigondozó Szolgálat', 'magyar-kozosseg', 'Egyház', 'Wien', 'Magyar egyház · Wien · reformatus.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-ausztriai-magyar-szervezetek-kozponti-szovetsege', 'Ausztriai Magyar Szervezetek Központi Szövetsége', 'magyar-kozosseg', 'Ernyőszervezet', 'Wien', 'Magyar ernyőszervezet · Wien · kozpontiszovetseg.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-ausztriai-magyar-szervezetek-kerekasztala', 'Ausztriai Magyar Szervezetek Kerekasztala', 'magyar-kozosseg', 'Ernyőszervezet', 'Wien', 'Magyar ernyőszervezet · Wien · kerekasztal.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-becsi-foegyhazmegye-magyar-kozossege', 'Bécsi Főegyházmegye Magyar Közössége', 'magyar-kozosseg', 'Egyház', 'Wien', 'Magyar egyház · Wien · katolikus.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-becsi-magyar-iskolaegyesulet', 'Bécsi Magyar Iskolaegyesület', 'magyar-kozosseg', 'Iskola', 'Wien', 'Magyar iskola · Wien · ungarischlernen.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-becsi-magyar-munkasegylet', 'Bécsi Magyar Munkásegylet', 'magyar-kozosseg', 'Egyesület', 'Wien', 'Magyar egyesület · Wien', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-bornemisza-peter-tarsasag', 'Bornemisza Péter Társaság', 'magyar-kozosseg', 'Irodalmi társaság', 'Wien', 'Magyar irodalmi társaság · Wien · kozpontiszovetseg.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-brand-art-studio-wien', 'Brand Art Studio Wien', 'magyar-kozosseg', 'Kultúra', 'Wien', 'Magyar kultúra · Wien · brandart.studio', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-club-pannonia', 'Club Pannonia', 'magyar-kozosseg', 'Klub', 'Wien', 'Magyar klub · Wien · club-pannonia.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-delibab-becsi-magyar-kulturegyesulet', 'Délibáb Bécsi Magyar Kultúregyesület', 'magyar-kozosseg', 'Kultúra', 'Wien', 'Magyar kultúra · Wien · wukv.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-erdelyi-magyarok-ausztriai-egyesulete', 'Erdélyi Magyarok Ausztriai Egyesülete', 'magyar-kozosseg', 'Egyesület', 'Wien', 'Magyar egyesület · Wien', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-europa-club', 'EUROPA-CLUB', 'magyar-kozosseg', 'Kultúra', 'Wien', 'Magyar kultúra · Wien · europaclub.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-kalaka-club', 'Kaláka-Club', 'magyar-kozosseg', 'Gazdasági érdekkör', 'Wien', 'Magyar gazdasági érdekkör · Wien · kalaka-club.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-lean-in-femspace', 'Lean in Femspace', 'magyar-kozosseg', 'Női közösség', 'Wien', 'Magyar női közösség · Wien', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-napraforgok', 'Napraforgók', 'magyar-kozosseg', 'Néptánc / népzene', 'Wien', 'Magyar néptánc / népzene · Wien · napraforgok.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-osztrak-magyar-tarsasag', 'Osztrák-Magyar Társaság', 'magyar-kozosseg', 'Társaság', 'Wien', 'Magyar társaság · Wien · goeu.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-svung', 'SVUNG', 'magyar-kozosseg', 'Művészet', 'Wien', 'Magyar művészet · Wien · svung.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-72-sz-becsi-szechenyi-istvan-cserkeszcsapat', '72. sz. bécsi Széchenyi István Cserkészcsapat', 'magyar-kozosseg', 'Cserkészet', 'Wien', 'Magyar cserkészet · Wien · cserkesz.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-alsoori-enekkar', 'Alsóőri Énekkar', 'magyar-kozosseg', 'Kórus', 'Alsóőr / Unterwart', 'Magyar kórus · Alsóőr / Unterwart', '["Magyar"]', 47.2667, 16.2167, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'BGL');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-alsoori-katolikus-egyhazkozseg', 'Alsóőri Katolikus Egyházközség', 'magyar-kozosseg', 'Egyház', 'Alsóőr / Unterwart', 'Magyar egyház · Alsóőr / Unterwart · martinus.at/unterwart', '["Magyar"]', 47.2667, 16.2167, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'BGL');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-alsoori-ketnyelvu-szinjatszoegyesulet', 'Alsóőri Kétnyelvű Színjátszóegyesület', 'magyar-kozosseg', 'Színház', 'Alsóőr / Unterwart', 'Magyar színház · Alsóőr / Unterwart · theaterverein-unterwart.at', '["Magyar"]', 47.2667, 16.2167, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'BGL');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-alsoori-otthon', 'Alsóőri Otthon', 'magyar-kozosseg', 'Kultúrház', 'Alsóőr / Unterwart', 'Magyar kultúrház · Alsóőr / Unterwart', '["Magyar"]', 47.2667, 16.2167, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'BGL');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-alsoori-vasjobbagyi-magyar-barati-kor', 'Alsóőri-Vasjobbágyi Magyar Baráti Kör', 'magyar-kozosseg', 'Baráti kör', 'Alsóőr', 'Magyar baráti kör · Alsóőr', '["Magyar"]', 47.2667, 16.2167, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'BGL');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-burgenlandi-magyar-kulturegyesulet', 'Burgenlandi Magyar Kultúregyesület', 'magyar-kozosseg', 'Kultúra', 'Burgenland', 'Magyar kultúra · Burgenland · bukv.at', '["Magyar"]', 47.8457, 16.5278, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'BGL');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-burgenlandi-magyarok-nepfoiskolaja', 'Burgenlandi Magyarok Népfőiskolája', 'magyar-kozosseg', 'Oktatás', 'Burgenland', 'Magyar oktatás · Burgenland · vhs-ungarn.at', '["Magyar"]', 47.8457, 16.5278, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'BGL');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-eszak-burgenlandi-magyar-kulturalis-egyesulet', 'Észak-burgenlandi Magyar Kulturális Egyesület', 'magyar-kozosseg', 'Kultúra', 'Észak-Burgenland', 'Magyar kultúra · Észak-Burgenland', '["Magyar"]', 47.8457, 16.5278, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'BGL');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-felsoori-katolikus-egyhazkozseg', 'Felsőőri Katolikus Egyházközség', 'magyar-kozosseg', 'Egyház', 'Felsőőr / Oberwart', 'Magyar egyház · Felsőőr / Oberwart · martinus.at/oberwart', '["Magyar"]', 47.2853, 16.2003, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'BGL');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-felsoori-reformatus-gyulekezet', 'Felsőőri Református Gyülekezet', 'magyar-kozosseg', 'Egyház', 'Felsőőr / Oberwart', 'Magyar egyház · Felsőőr / Oberwart · die-reformierten.at', '["Magyar"]', 47.2853, 16.2003, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'BGL');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-kozep-burgenlandi-magyar-kulturegyesulet', 'Közép-burgenlandi Magyar Kultúregyesület', 'magyar-kozosseg', 'Kultúra', 'Közép-Burgenland', 'Magyar kultúra · Közép-Burgenland', '["Magyar"]', 47.8457, 16.5278, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'BGL');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-magyar-kultur-es-tancegyesulet-alsoor', 'Magyar Kultúr- és Táncegyesület Alsóőr', 'magyar-kozosseg', 'Tánc / kultúra', 'Alsóőr / Unterwart', 'Magyar tánc / kultúra · Alsóőr / Unterwart', '["Magyar"]', 47.2667, 16.2167, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'BGL');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-magyar-media-es-informacios-kozpont-umiz', 'Magyar Média és Információs Központ (UMIZ)', 'magyar-kozosseg', 'Média / információ', 'Burgenland', 'Magyar média / információ · Burgenland · umiz.at', '["Magyar"]', 47.8457, 16.5278, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'BGL');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-oriszigeti-evangelikus-egyhazkozseg', 'Őriszigeti Evangélikus Egyházközség', 'magyar-kozosseg', 'Egyház', 'Őrisziget / Siget in der Wart', 'Magyar egyház · Őrisziget / Siget in der Wart · evang-bgld.at', '["Magyar"]', 47.25, 16.2333, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'BGL');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-reformatus-ifjusagi-olvasokor', 'Református Ifjúsági Olvasókör', 'magyar-kozosseg', 'Ifjúsági', 'Felsőőr / Oberwart', 'Magyar ifjúsági · Felsőőr / Oberwart', '["Magyar"]', 47.2853, 16.2003, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'BGL');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-grazi-magyar-egyesulet', 'Grazi Magyar Egyesület', 'magyar-kozosseg', 'Kultúra', 'Graz', 'Magyar kultúra · Graz · grazimagyaregyesuelet.at', '["Magyar"]', 47.0707, 15.4395, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'STM');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-graci-magyar-katolikus-kozosseg', 'Gráci Magyar Katolikus Közösség', 'magyar-kozosseg', 'Egyház', 'Graz', 'Magyar egyház · Graz', '["Magyar"]', 47.0707, 15.4395, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'STM');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-hungaromedia', 'HungaroMedia', 'magyar-kozosseg', 'Média', 'Graz', 'Magyar média · Graz', '["Magyar"]', 47.0707, 15.4395, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'STM');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-magyar-egyetemistak-es-oregdiakok-klubja', 'Magyar Egyetemisták és Öregdiákok Klubja', 'magyar-kozosseg', 'Diák / öregdiák', 'Graz', 'Magyar diák / öregdiák · Graz · meoek.at', '["Magyar"]', 47.0707, 15.4395, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'STM');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-felso-ausztriai-magyarok-kulturegyesulete', 'Felső-Ausztriai Magyarok Kultúregyesülete', 'magyar-kozosseg', 'Kultúra', 'Felső-Ausztria', 'Magyar kultúra · Felső-Ausztria', '["Magyar"]', 48.3064, 14.2861, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'OOE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-felso-ausztriai-hetvegi-magyar-ovoda-es-iskola', 'Felső-Ausztriai Hétvégi Magyar Óvoda és Iskola', 'magyar-kozosseg', 'Iskola / óvoda', 'Felső-Ausztria', 'Magyar iskola / óvoda · Felső-Ausztria', '["Magyar"]', 48.3064, 14.2861, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'OOE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-linzi-magyar-katolikus-kozosseg', 'Linzi Magyar Katolikus Közösség', 'magyar-kozosseg', 'Egyház', 'Linz', 'Magyar egyház · Linz', '["Magyar"]', 48.3064, 14.2861, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'OOE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-ne-felejts-neptancegyuttes', 'Ne-Felejts! Néptáncegyüttes', 'magyar-kozosseg', 'Néptánc', 'Linz', 'Magyar néptánc · Linz · ne-felejts.weebly.com', '["Magyar"]', 48.3064, 14.2861, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'OOE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-80-sz-arpad-cserkeszcsapat-wels', '80. sz. Árpád Cserkészcsapat Wels', 'magyar-kozosseg', 'Cserkészet', 'Wels', 'Magyar cserkészet · Wels · wels.cserkesz.eu', '["Magyar"]', 48.1575, 14.0289, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'OOE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-innsbrucki-magyar-diakotthon-es-kulturcentrum', 'Innsbrucki Magyar Diákotthon és Kultúrcentrum', 'magyar-kozosseg', 'Diákotthon / kultúra', 'Innsbruck', 'Magyar diákotthon / kultúra · Innsbruck · magyarhaz.at', '["Magyar"]', 47.2692, 11.4041, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'TIR');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-innsbrucki-magyar-egyetemistak-es-akademikusok-szovetsege', 'Innsbrucki Magyar Egyetemisták és Akadémikusok Szövetsége', 'magyar-kozosseg', 'Diák / akadémiai', 'Innsbruck', 'Magyar diák / akadémiai · Innsbruck', '["Magyar"]', 47.2692, 11.4041, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'TIR');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-innsbrucki-magyar-ifjusagi-es-kulturegyesulet', 'Innsbrucki Magyar Ifjúsági és Kultúregyesület', 'magyar-kozosseg', 'Ifjúsági / kultúra', 'Innsbruck', 'Magyar ifjúsági / kultúra · Innsbruck', '["Magyar"]', 47.2692, 11.4041, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'TIR');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-79-sz-dr-kozma-gyorgy-sj-cserkeszcsapat', '79. sz. Dr. Kozma György SJ Cserkészcsapat', 'magyar-kozosseg', 'Cserkészet', 'Innsbruck', 'Magyar cserkészet · Innsbruck', '["Magyar"]', 47.2692, 11.4041, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'TIR');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-salzburgi-magyar-egyesulet', 'Salzburgi Magyar Egyesület', 'magyar-kozosseg', 'Kultúra', 'Salzburg', 'Magyar kultúra · Salzburg · salzung.com', '["Magyar"]', 47.8095, 13.055, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'SBG');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-mi-magyarok-egymasert', 'Mi Magyarok Egymásért', 'magyar-kozosseg', 'Segélyegyesület', 'Vorarlberg', 'Magyar segélyegyesület · Vorarlberg', '["Magyar"]', 47.5031, 9.7471, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'VBG');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-vorarlbergi-magyar-egyesulet', 'Vorarlbergi Magyar Egyesület', 'magyar-kozosseg', 'Kultúra', 'Vorarlberg', 'Magyar kultúra · Vorarlberg', '["Magyar"]', 47.5031, 9.7471, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'VBG');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-egyesulet-a-magyar-kulturaert-karintiaban', 'Egyesület a Magyar Kultúráért Karintiában', 'magyar-kozosseg', 'Kultúra', 'Kärnten', 'Magyar kultúra · Kärnten', '["Magyar"]', 46.6247, 14.305, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'KTN');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-becsujhely-es-kornyeki-magyarok-kulturalis-egyesulete', 'Bécsújhely és környéki Magyarok Kulturális Egyesülete', 'magyar-kozosseg', 'Kultúra', 'Wiener Neustadt', 'Magyar kultúra · Wiener Neustadt', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'NOE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-vipach-becsi-magyar-fotoklub', 'VIPACH – Bécsi Magyar Fotóklub', 'magyar-kozosseg', 'Fotóklub', 'Wien', 'Magyar fotóklub · Wien · vipach.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-becsi-naplo', 'Bécsi Napló', 'magyar-kozosseg', 'Magyar lap', 'Wien', 'Magyar magyar lap · Wien · www.becsinaplo.at/', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-becsi-szelet-kulturalis-es-muveszeti-magazin', 'Bécsi Szelet – Kulturális és Művészeti Magazin', 'magyar-kozosseg', 'Kulturális magazin', 'Wien', 'Magyar kulturális magazin · Wien · becsiszelet.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-becsi-magyar-musical-tarsulat', 'Bécsi Magyar Musical Társulat', 'magyar-kozosseg', 'Musical társulat', 'Wien', 'Magyar musical társulat · Wien · musicaltarsulat.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-at-org', 'AT', 'W');
