-- db/seed-ch.sql — AUTOGENERÁLT (scripts/gen-ch-seed.mjs). NE szerkeszd kézzel.
-- Valódi svájci magyar szervezetek (forrás: berni nagykövetség hivatalos jegyzéke). Alkalmazás:
--   wrangler d1 execute kinti-db --remote --file=./db/seed-ch.sql

-- 1) Közösség-kategória (ország-független, OR IGNORE — az AT/DE-seed is ezt használja).
INSERT OR IGNORE INTO categories (id, label, glyph, sort_order) VALUES ('magyar-kozosseg', 'Magyar közösség / egyesület', '🇭🇺', 900);

-- 2) Szervezetek (country_code='CH', kanton a canton_code-ban, jóváhagyva, nem foglalt).
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-bazeli-katolikus-magyar-misszio', 'Bázeli Katolikus Magyar Misszió', 'magyar-kozosseg', 'Katolikus misszió', 'Basel', 'Magyar katolikus misszió · Basel · www.ungarnmission.ch', '["Magyar"]', 47.5596, 7.5886, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'BS');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-genfi-magyar-egyesulet', 'Genfi Magyar Egyesület', 'magyar-kozosseg', 'Egyesület', 'Genf', 'Magyar egyesület · Genf · ahg.ch', '["Magyar"]', 46.2044, 6.1432, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'GE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-genfi-magyar-kulturalis-kozpont', 'Genfi Magyar Kulturális Központ', 'magyar-kozosseg', 'Kulturális központ', 'Genf', 'Magyar kulturális központ · Genf · www.genfimagyarkultura.com', '["Magyar"]', 46.2044, 6.1432, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'GE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-magyar-mernokok-es-epiteszek-svajci-egyesulete-mmese', 'Magyar Mérnökök és Építészek Svájci Egyesülete (MMÉSE)', 'magyar-kozosseg', 'Mérnök-egyesület', 'Zürich', 'Magyar mérnök-egyesület · Zürich · www.mmese.ch', '["Magyar"]', 47.3769, 8.5417, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'ZH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-svajci-magyar-egyesulet-hagyomanyos-ijaszat', 'Svájci Magyar Egyesület – Hagyományos Íjászat', 'magyar-kozosseg', 'Íjász-egyesület', 'Zürich', 'Magyar íjász-egyesület · Zürich · www.ijaszat.ch', '["Magyar"]', 47.3769, 8.5417, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'ZH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-svajci-magyarhaz-alapitvany', 'Svájci Magyarház Alapítvány', 'magyar-kozosseg', 'Magyar ház / alapítvány', 'Zürich', 'Magyar ház / alapítvány · Zürich · www.magyarhaz.ch', '["Magyar"]', 47.3769, 8.5417, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'ZH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-zurichi-magyar-tortenelmi-egyesulet', 'Zürichi Magyar Történelmi Egyesület', 'magyar-kozosseg', 'Történelmi egyesület', 'Zürich', 'Magyar történelmi egyesület · Zürich · www.zmte.org', '["Magyar"]', 47.3769, 8.5417, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'ZH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-svajci-magyarnyelvu-protestans-gyulekezetek-szovetsege', 'Svájci Magyarnyelvű Protestáns Gyülekezetek Szövetsége', 'magyar-kozosseg', 'Protestáns gyülekezet', 'Zürich', 'Magyar protestáns gyülekezet · Zürich · www.protestans.ch', '["Magyar"]', 47.3769, 8.5417, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'ZH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-bazeli-magyar-iskola-es-ovoda-egyesulet', 'Bázeli Magyar Iskola és Óvoda Egyesület', 'magyar-kozosseg', 'Iskola és óvoda', 'Basel', 'Magyar iskola és óvoda · Basel · www.ovi-suli.ch', '["Magyar"]', 47.5596, 7.5886, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'BS');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-genfi-magyar-iskola-es-ovoda', 'Genfi Magyar Iskola és Óvoda', 'magyar-kozosseg', 'Iskola és óvoda', 'Genf', 'Magyar iskola és óvoda · Genf · genfimagyariskola.wixsite.com/website', '["Magyar"]', 46.2044, 6.1432, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'GE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-thurgaui-magyar-iskola-es-ovoda', 'Thurgaui Magyar Iskola és Óvoda', 'magyar-kozosseg', 'Iskola és óvoda', 'Kreuzlingen', 'Magyar iskola és óvoda · Kreuzlingen · ungarischervereinthurgau.ch', '["Magyar"]', 47.651, 9.1745, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'TG');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-zurichi-magyar-iskola-es-ovoda', 'Zürichi Magyar Iskola és Óvoda', 'magyar-kozosseg', 'Iskola és óvoda', 'Zürich', 'Magyar iskola és óvoda · Zürich · www.magyar-iskola.ch', '["Magyar"]', 47.3769, 8.5417, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'ZH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-berni-magyar-iskola-es-ovoda', 'Berni Magyar Iskola és Óvoda', 'magyar-kozosseg', 'Iskola és óvoda', 'Bern', 'Magyar iskola és óvoda · Bern · iskola.bernimagyarok.org', '["Magyar"]', 46.948, 7.4474, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'BE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-berni-magyar-cserkeszcsapat', 'Berni Magyar Cserkészcsapat', 'magyar-kozosseg', 'Cserkészcsapat', 'Bern', 'Magyar cserkészcsapat · Bern · cserkeszet.bernimagyarok.org', '["Magyar"]', 46.948, 7.4474, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'BE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-badeni-magyar-ovoda-es-iskola-csillaghajo', 'Badeni Magyar Óvoda és Iskola (Csillaghajó)', 'magyar-kozosseg', 'Óvoda és iskola', 'Baden', 'Magyar óvoda és iskola · Baden · csillaghajo.ch', '["Magyar"]', 47.4737, 8.308, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'AG');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('ch-zurichi-magyar-cserkeszcsapat', 'Zürichi Magyar Cserkészcsapat', 'magyar-kozosseg', 'Cserkészcsapat', 'Zürich', 'Magyar cserkészcsapat · Zürich · cserkesz.ch', '["Magyar"]', 47.3769, 8.5417, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-ch-org', 'CH', 'ZH');
