-- db/seed-gb.sql — AUTOGENERÁLT (scripts/gen-gb-seed.mjs). NE szerkeszd kézzel.
-- Valódi angliai magyar szervezetek, ellenőrzött elérhetőséggel. Alkalmazás:
--   wrangler d1 execute kinti-db --remote --file=./db/seed-gb.sql

-- 1) Közösség-kategória (ország-független, OR IGNORE — a többi seed is ezt használja).
INSERT OR IGNORE INTO categories (id, label, glyph, sort_order) VALUES ('magyar-kozosseg', 'Magyar közösség / egyesület', '🇭🇺', 900);

-- 2) Szervezetek (country_code='GB', régió a canton_code-ban, jóváhagyva, nem foglalt).
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-szent-istvan-haz-angliai-romai-katolikus-magyarok-egyesulete', 'Szent István Ház — Angliai Római Katolikus Magyarok Egyesülete (ARKME)', 'magyar-kozosseg', 'Katolikus közösségi ház', '62 Little Ealing Lane, London W5 4EA', NULL, 'hello@szentistvanhaz.org', 'Katolikus közösségi ház · London · szentistvanhaz.org', '["Magyar"]', 51.5074, -0.1278, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-angliai-magyar-reformatus-egyhaz', 'Angliai Magyar Református Egyház', 'magyar-kozosseg', 'Református gyülekezet', '17 St Dunstan''s Road, London W6 8RD', '+44 20 8748 8858', 'info@reflondon.hu', 'Református gyülekezet · London · reflondon.hu', '["Magyar"]', 51.5074, -0.1278, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-magyar-kulturalis-kozpont-london', 'Magyar Kulturális Központ London', 'magyar-kozosseg', 'Kulturális központ', '10 Maiden Lane, Covent Garden, London WC2E 7NA', '+44 20 7257 2023', NULL, 'Kulturális központ · London · www.hungary.org.uk', '["Magyar"]', 51.5074, -0.1278, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-magyarorszag-nagykovetsege-london', 'Magyarország Nagykövetsége — London', 'magyar-kozosseg', 'Nagykövetség', '35 Eaton Place, London SW1X 8BY', '+44 20 7201 3440', 'mission.lon@mfa.gov.hu', 'Nagykövetség · London · london.mfa.gov.hu', '["Magyar"]', 51.5074, -0.1278, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-magyarorszag-nagykovetsege-konzuli-osztaly', 'Magyarország Nagykövetsége — Konzuli Osztály', 'magyar-kozosseg', 'Konzuli osztály', '100 Brompton Road, London SW3 1ER', '+44 20 7235 5218', 'consulate.lon@mfa.gov.hu', 'Konzuli osztály · London · london.mfa.gov.hu', '["Magyar"]', 51.5074, -0.1278, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-londoni-magyar-iskola', 'Londoni Magyar Iskola+', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'London', NULL, 'LMIplusz@gmail.com', 'Hétvégi magyar iskola · London · magyariskola.org.uk', '["Magyar"]', 51.5074, -0.1278, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-mosoly-magyar-ovi-suli', 'MOSOLY Magyar Ovi-Suli', 'magyar-kozosseg', 'Hétvégi magyar óvoda és iskola', 'London', '+44 7961 441041', 'info@magyarovisuli.co.uk', 'Hétvégi magyar óvoda és iskola · London · magyarovisuli.co.uk', '["Magyar"]', 51.5074, -0.1278, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-maki-suli-london', 'MAKI Suli London', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'London', NULL, 'makisulilondon@gmail.com', 'Hétvégi magyar iskola · London · makisulilondon.wixsite.com/maki', '["Magyar"]', 51.5074, -0.1278, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'LDN');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-birminghami-magyar-tanoda-es-kulturalis-kozpont', 'Birminghami Magyar Tanoda és Kulturális Központ', 'magyar-kozosseg', 'Hétvégi magyar iskola és kulturális központ', 'Selly Oak Methodist Church, Langleys Road, Birmingham B29 6HT', '+44 7756 214875', 'birminghamiskola@gmail.com', 'Hétvégi magyar iskola és kulturális központ · Birmingham · birminghamimagyarok.org', '["Magyar"]', 52.4862, -1.8904, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'WM');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-coventry-magyar-tanoda-es-kozosseg', 'Coventry Magyar Tanoda és Közösség', 'magyar-kozosseg', 'Hétvégi magyar iskola és közösség', 'Coventry', NULL, 'coventrymagyartanoda@gmail.com', 'Hétvégi magyar iskola és közösség · Coventry · comat.org.uk', '["Magyar"]', 52.4068, -1.5197, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'WM');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-zsigmond-kiraly-magyar-kulturalis-klub-es-iskola', 'Zsigmond Király Magyar Kulturális Klub és Iskola', 'magyar-kozosseg', 'Magyar kulturális klub és hétvégi iskola', 'Manchester', NULL, 'zsk.iskola@gmail.com', 'Magyar kulturális klub és hétvégi iskola · Manchester · zsigmondkiraly.co.uk', '["Magyar"]', 53.4808, -2.2426, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'NW');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-magyar-iskola-cambridge', 'Magyar Iskola Cambridge', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Cambridge', NULL, 'magyariskolacambridge@gmail.com', 'Hétvégi magyar iskola · Cambridge', '["Magyar"]', 52.2053, 0.1218, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'EE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-st-albans-i-magyar-iskola', 'St Albans-i Magyar Iskola', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'St Albans', NULL, 'hungarianschoolofstalbans@gmail.com', 'Hétvégi magyar iskola · St Albans · www.hungarianschool.co.uk', '["Magyar"]', 51.752, -0.3369, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'EE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-guildfordi-magyar-tanoda-es-jatszohaz', 'Guildfordi Magyar Tanoda és Játszóház', 'magyar-kozosseg', 'Hétvégi magyar iskola és játszóház', 'Guildford', '+44 1483 808643', 'info@hcaguildford.org.uk', 'Hétvégi magyar iskola és játszóház · Guildford · hcaguildford.org.uk', '["Magyar"]', 51.2362, -0.5704, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'SE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-readingi-magyar-iskola', 'Readingi Magyar Iskola', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Reading', '+44 7533 337720', 'readingi.magyar.iskola@gmail.com', 'Hétvégi magyar iskola · Reading', '["Magyar"]', 51.4543, -0.9781, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'SE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-magyar-iskola-woking', 'Magyar Iskola Woking', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Woking', NULL, 'info@magyariskolawoking.org.uk', 'Hétvégi magyar iskola · Woking · magyariskolawoking.org.uk', '["Magyar"]', 51.3168, -0.561, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'SE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-magyar-iskola-oxford', 'Magyar Iskola Oxford', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Oxford', NULL, 'hunschoolox@gmail.com', 'Hétvégi magyar iskola · Oxford', '["Magyar"]', 51.752, -1.2577, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'SE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-basingstoke-i-magyar-ovi-es-suli', 'Basingstoke-i Magyar Ovi és Suli', 'magyar-kozosseg', 'Hétvégi magyar óvoda és iskola', 'Basingstoke', '+44 7766 951790', 'basingstoke@magyar.org.uk', 'Hétvégi magyar óvoda és iskola · Basingstoke', '["Magyar"]', 51.2665, -1.0873, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'SE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-southamptoni-magyar-iskola', 'Southamptoni Magyar Iskola', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Southampton', NULL, 'hello@southamptonimagyariskola.org.uk', 'Hétvégi magyar iskola · Southampton · southamptonimagyariskola.org.uk', '["Magyar"]', 50.9097, -1.4044, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'SE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, phone, contact_email, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('gb-bristoli-magyar-kisiskola', 'Bristoli Magyar Kisiskola', 'magyar-kozosseg', 'Hétvégi magyar iskola', 'Bristol', NULL, NULL, 'Hétvégi magyar iskola · Bristol · bristolikisiskola.org', '["Magyar"]', 51.4545, -2.5879, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-gb-org', 'GB', 'SW');
