-- db/seed-nmde.sql — VALÓDI németországi magyar vállalkozások a nemetorszagi-magyarok.de
-- aktívan karbantartott katalógusából (Drupal JSON:API), korábban le nem fedett kategóriák
-- (tetováló, fotós, kisvárosi boltok, autókereskedés) + friss 2026-os feltöltések.
-- Cím a forrásé, koordináta Nominatim-geokód (bbox-validált). Dedupolva a teljes élő tábla ellen.
-- Alkalmazás: printf 'y\n' | wrangler d1 execute kinti-db --remote --file=./db/seed-nmde.sql

INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-da-flava-tattoo-studio-stuttgart','Da Flava Tattoo Studio Stuttgart','tetovalas','Tetováló / Piercing','Forststraße 62 A, 70176 Stuttgart','+4971162054952','Tetováló / Piercing · www.da-flava-tattoos.de','["Magyar"]',48.7792786,9.1610956,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-marton-anita-forditoiroda','Marton Anita / Fordítóiroda','fordito','Fordító','Kaiserstraße 60, 90762 Fürth','+49 15731850016','Fordító · anita-marton.de','["Magyar"]',49.4630855,10.9909857,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-zelizi-petra-viselkedeselemzo-pszichologus-onfejle','Zelizi Petra Viselkedéselemző, Pszichológus, Önfejlesztési Tanácsadó','pszichologus','Pszichológus / Coach','Steiermärker Str. 3-5, 70469 Stuttgart',NULL,'Pszichológus / Coach · zelizipetra.hu','["Magyar"]',48.8143644,9.165389,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-ungarische-welt-magyar-bolt-nittenau','Ungarische Welt, magyar bolt, Nittenau','elelmiszer','Magyar bolt / élelmiszer','Hauptstraße 4 93149, Nittenau',NULL,'Magyar bolt / élelmiszer · ungarischewelt.com','["Magyar"]',49.1977477,12.272969,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-ungarnservice','Ungarnservice','elelmiszer','Magyar bolt / élelmiszer','Weingartener Str. 9, Stutensee',NULL,'Magyar bolt / élelmiszer · www.ungarnservice.de','["Magyar"]',49.0927513,8.5103962,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-tattoo-naherei-tubingen','Tattoo Näherei, Tübingen','tetovalas','Tetováló / Piercing','Wilhelmstrasse 3/1, Tübingen','+491626988171','Tetováló / Piercing · bit.ly/TattooNaherei','["Magyar"]',48.5227552,9.0583808,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-ungarische-wurst-delicatessen','Ungarische Wurst & Delicatessen','elelmiszer','Magyar bolt / élelmiszer','Karwendelstr 2, 82492 Krün','+4915161382604','Magyar bolt / élelmiszer · bit.ly/3jz4VFj','["Magyar"]',47.5051828,11.2781078,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-ungarikum-delikatesse-magyar-bolt-metten','Ungarikum Delikatesse, magyar bolt, Metten','elelmiszer','Magyar bolt / élelmiszer','Donaustraße 11. 94526 Metten',NULL,'Magyar bolt / élelmiszer · www.ungarikumdelikatesse.de/kontakt','["Magyar"]',48.853869,12.914606,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-magyar-kozmetikus-schwabachban-calmeza-kosmetik-es','Magyar kozmetikus Schwabachban, Calmeza Kosmetik és Wellness','szepseg','Kozmetikus','Wolkersdorfer Hauptstrasse 25b, 91126 Schwabach','+4991113210662','Kozmetikus · www.calmeza.de/ausbildungen-seminare','["Magyar"]',49.3617891,11.028155,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-david-energy-tattoo-nurnberg','David Energy Tattoo, Nürnberg','tetovalas','Tetováló / Piercing','Färberstraße 54, 90402 Nürnberg','+4917640731820','Tetováló / Piercing · www.davidenergytattoo.de/tattoos','["Magyar"]',49.4479256,11.0717451,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-laszlo-tattoo-nurnberg','László Tattoo, Nürnberg','tetovalas','Tetováló / Piercing','Enderleinstr. 8, 90478 Nürnberg','+4917664062078','Tetováló / Piercing · www.facebook.com/TattooTempleNurnberg','["Magyar"]',49.4424169,11.0906079,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-sweet-pain-inc-tetovalas-langenzenn','Sweet Pain INC - tetoválás, Langenzenn','tetovalas','Tetováló / Piercing','Würzburger Straße 14, 90579 Langenzenn','+4915163384556','Tetováló / Piercing · www.facebook.com/sweetpain.inc','["Magyar"]',49.5084931,10.7741579,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-zoli-s-extrawurst-und-fertig-magyar-etterem-espasi','Zoli''s Extrawurst und_fertig, magyar étterem, Espasingen','etterem','Étterem','Meersburger Str. 4, 78333 Espasingen','+4915168750792','Étterem · www.zolis-extrawurst-und-fertig.de/aktuell','["Magyar"]',47.8182882,9.0123594,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-ungarnladen-magyar-bolt-sulzetal','Ungarnladen, magyar bolt, Sülzetal','elelmiszer','Magyar bolt / élelmiszer','Dorfstraße 3a, 39171 Sülzetal','+493916074643','Magyar bolt / élelmiszer · ungarnladen.de','["Magyar"]',52.0388442,11.6127995,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','ST');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-car-kitchen-magyar-bar-es-grill-deggendorfban','CAR KITCHEN, magyar bar és grill Deggendorfban','etterem','Étterem','Hauptstr. 45, 94469 Deggendorf','+4999127003932','Étterem · www.facebook.com/carkitchendeggendorf','["Magyar"]',48.8239842,12.9399762,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-mir-auto-autokereskedes-sinsheimban','MIR Auto - Autókereskedés Sinsheimban','autokereskedes','Autókereskedés','Danziger str 20, 74889 Sinsheim','+4917674593667','Autókereskedés · www.facebook.com/roland.dozsa','["Magyar"]',49.2386865,8.9040429,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-turcsanyi-photography-deinsportbild-de','Turcsanyi Photography, DEINSPORTBILD.de','fotos','Fotós','88299 Leutkirch, Falkenweg 18','+4915112306438','Fotós · DEINSPORTBILD.de','["Magyar"]',47.8305673,10.0334111,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-sunmoon-kosmetikstudio-magyar-kozmetikus-schenkenz','SunMoon Kosmetikstudio, magyar kozmetikus, Schenkenzell','szepseg','Kozmetikus','Talstr 26, 77773 Schenkenzell','+4915174333557','Kozmetikus · www.facebook.com/SunMoonKosmetikstudio','["Magyar"]',48.3547694,8.3481409,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-landhaus-rosenbrau-magyar-etterem-turkheim','Landhaus Rosenbräu, magyar étterem, Türkheim','etterem','Étterem','Mindelheimer Straße 2, 86842 Türkheim','+4982454365','Étterem · bit.ly/Landhauss','["Magyar"]',48.0436625,10.6207389,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-balazs-edit-fordito-dresden-neustadt','Balázs Edit, fordító, Dresden-Neustadt','fordito','Fordító','Zittauer Str. 1, 01099 Drezda','+493515635200','Fordító · www.uebersetzungen-ungarisch.de/ungarisch/A','["Magyar"]',51.0663098,13.7642447,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','SN');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-magyar-bolt-es-kavezo-elben-mehr-als-backerei','Magyar bolt és kavézó, ElBen mehr als Bäckerei','etterem','Étterem','Bahnhofstrasse 47/1, 73312 Geislingen an der Steige','+4915166485878','Étterem · bit.ly/magyarboltésétterem','["Magyar"]',48.6196235,9.8410215,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-made-in-hungaria-ungarische-spezialitaten-magyar-b','Made in Hungaria - ungarische Spezialitäten, magyar bolt','elelmiszer','Magyar bolt / élelmiszer','Schwandorf 92421, Pfleghofstufen 2',NULL,'Magyar bolt / élelmiszer · bit.ly/Made-in-Hungaria-ungarische-Speziali','["Magyar"]',49.3313019,12.1078125,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-nb-center-gmbh-autoszerelo-autokereskedo-northeim','NB-Center GmbH, autószerelő, autókereskedő, Northeim','autokereskedes','Autókereskedés','Robert-Bosch Straße 17, 37154 Northeim','+4955519082823','Autókereskedés · bit.ly/NB-CenterGmbH','["Magyar"]',51.6840469,9.9832177,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','NI');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-feri-s-markt-ungarische-spezialitaten-dortmund','Feri''s Markt Ungarische Spezialitäten, Dortmund','elelmiszer','Magyar bolt / élelmiszer','Färber strasse 17, 44329 Dortmund','+4915163728206','Magyar bolt / élelmiszer · bit.ly/feri-markt','["Magyar"]',51.5794972,7.5637509,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','NW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-piroschkas-lieblingsplatz-magyar-bolt-viechtach','Piroschkas Lieblingsplatz, magyar bolt, Viechtach','elelmiszer','Magyar bolt / élelmiszer','Mönchshofstr. 10, 94234 Viechtach','+4915144905654','Magyar bolt / élelmiszer · www.facebook.com/Piroschkaslieblingsplatz','["Magyar"]',49.076028,12.889069,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-scheune-varel-magyar-etterem','Scheune Varel, magyar étterem','etterem','Étterem','Obernstr. 7, 26316 Varel','+494451961818','Étterem · www.scheune-varel.de','["Magyar"]',53.3952747,8.1390411,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','NI');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-balaton-retro-magyar-etterem','Balaton Retro, magyar étterem','etterem','Étterem','Augsburger Str. 31 / B, 82194 Groebenzell','+4981426525947','Étterem · www.balaton-retro.de','["Magyar"]',48.1940297,11.3665762,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-gaststatte-zum-posthornle-etterem','Gaststätte zum Posthörnle, étterem','etterem','Étterem','Füssener Str. 31, 87471 Durach','+4983169728237','Étterem · www.tripadvisor.de/Restaurant_Review-g6517','["Magyar"]',47.6964394,10.3466566,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-ungarische-spezialitaten-linsengericht','Ungarische spezialitäten, Linsengericht','elelmiszer','Magyar bolt / élelmiszer','Im Hirtengarten 21, 63589 Linsengericht','+4960518858147','Magyar bolt / élelmiszer · johannreining58.wixsite.com/ungarischer-la','["Magyar"]',50.1627128,9.1717496,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','HE');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-szoke-krisztian-hites-szakfordito-nemet-magyar-mag','Szőke Krisztián hites szakfordító német-magyar, magyar-német','fordito','Fordító','Englmeierstr. 6b, Passau','+4916092567341','Fordító · www.ostsprachen-ubersetzerteam.de','["Magyar"]',48.5906586,13.4816524,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-aszautomobile-autokereskedes','ASZautomobile - autókereskedés','autokereskedes','Autókereskedés','Frankenbacher str 129, Heilbronn','+4917642084975','Autókereskedés · facebook.com/aszautomobile','["Magyar"]',49.1672841,9.191308,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-ex-cars-autokereskedes','Ex Cars Autókereskedés','autokereskedes','Autókereskedés','Alexander-Fleming-Straße 2 Viernheim 68519','+4917657981203','Autókereskedés · www.facebook.com/Ex-Cars-Autókereskedés','["Magyar"]',49.551155,8.5936724,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','HE');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-atrium-automobile','Atrium Automobile','autokereskedes','Autókereskedés','Füssener str. 52. 87640 Biessenhofen','+ 4983424202868','Autókereskedés · www.atriumautomobile.de','["Magyar"]',47.8181654,10.6438197,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BY');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-autokereskedes-heidenheim','Autokereskedés Heidenheim','autokereskedes','Autókereskedés','Würzburgerstrasse 72, Heidenheim 89518','+491728758989','Autókereskedés · www.facebook.com/Autokereskedes-Heidenheim','["Magyar"]',48.7044754,10.1637564,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BW');
INSERT OR IGNORE INTO businesses (id,name,category_id,category_label,address,phone,blurb,languages,lat,lng,pin_x,pin_y,rating,reviews,featured,open_now,moderation_status,claimed,hidden,verified,source,country_code,canton_code) VALUES ('de-nmde-menesi-csaba-fotos','Ménesi Csaba - fotós','fotos','Fotós','Burghaldenweg 32, 75378 Bad Liebenzell','+491758105876','Fotós · photomenesi.com','["Magyar"]',48.7799418,8.7211861,50,50,0,0,0,0,1,0,0,0,'seed-nmde','DE','BW');
