-- db/seed-hun-pop-at.sql — AUTOGENERÁLT (harvest-hun-population-at.mjs). NE szerkeszd kézzel.
-- Forrás: Statistik Austria, 'Bevölkerung zu Jahresbeginn nach detaillierter Staatsangehörigkeit'.
-- Élesítés: wrangler d1 execute kinti-db --remote --file=./db/seed-hun-pop-at.sql

INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('at-bgl-2026', 'AT', 'BGL', 'Burgenland', 'bundesland', 8872, 2026, 'Statistik Austria', 'https://www.statistik.at/fileadmin/pages/407/Bev_Staatsangeh_Bundesland_Zeitreihe.ods') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('at-ktn-2026', 'AT', 'KTN', 'Kärnten', 'bundesland', 4011, 2026, 'Statistik Austria', 'https://www.statistik.at/fileadmin/pages/407/Bev_Staatsangeh_Bundesland_Zeitreihe.ods') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('at-noe-2026', 'AT', 'NOE', 'Niederösterreich', 'bundesland', 17587, 2026, 'Statistik Austria', 'https://www.statistik.at/fileadmin/pages/407/Bev_Staatsangeh_Bundesland_Zeitreihe.ods') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('at-ooe-2026', 'AT', 'OOE', 'Oberösterreich', 'bundesland', 19944, 2026, 'Statistik Austria', 'https://www.statistik.at/fileadmin/pages/407/Bev_Staatsangeh_Bundesland_Zeitreihe.ods') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('at-sbg-2026', 'AT', 'SBG', 'Salzburg', 'bundesland', 8309, 2026, 'Statistik Austria', 'https://www.statistik.at/fileadmin/pages/407/Bev_Staatsangeh_Bundesland_Zeitreihe.ods') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('at-stm-2026', 'AT', 'STM', 'Steiermark', 'bundesland', 13762, 2026, 'Statistik Austria', 'https://www.statistik.at/fileadmin/pages/407/Bev_Staatsangeh_Bundesland_Zeitreihe.ods') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('at-tir-2026', 'AT', 'TIR', 'Tirol', 'bundesland', 8774, 2026, 'Statistik Austria', 'https://www.statistik.at/fileadmin/pages/407/Bev_Staatsangeh_Bundesland_Zeitreihe.ods') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('at-vbg-2026', 'AT', 'VBG', 'Vorarlberg', 'bundesland', 3496, 2026, 'Statistik Austria', 'https://www.statistik.at/fileadmin/pages/407/Bev_Staatsangeh_Bundesland_Zeitreihe.ods') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('at-w-2026', 'AT', 'W', 'Wien', 'bundesland', 30423, 2026, 'Statistik Austria', 'https://www.statistik.at/fileadmin/pages/407/Bev_Staatsangeh_Bundesland_Zeitreihe.ods') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
