-- db/seed-de.sql — AUTOGENERÁLT (scripts/gen-de-seed.mjs). NE szerkeszd kézzel.
-- Valódi németországi magyar szervezetek. Alkalmazás a 0081 + 0083 migráció UTÁN:
--   wrangler d1 execute kinti-db --remote --file=./db/seed-de.sql

-- 1) Közösség-kategória (ország-független, OR IGNORE — AT-seed is ezt használja).
INSERT OR IGNORE INTO categories (id, label, glyph, sort_order) VALUES ('magyar-kozosseg', 'Magyar közösség / egyesület', '🇭🇺', 900);

-- 2) Szervezetek (country_code='DE', régió a canton_code-ban, jóváhagyva, nem foglalt).
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-liszt-institut-magyar-kulturalis-intezet-stuttgart', 'Liszt-Institut – Magyar Kulturális Intézet Stuttgart', 'magyar-kozosseg', 'Kulturális intézet', 'Stuttgart', 'Magyar kulturális intézet · Stuttgart · culture.hu/de/stuttgart', '["Magyar"]', 48.7758, 9.1829, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'BW');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-deutsch-ungarische-gesellschaft-stuttgart', 'Deutsch-Ungarische Gesellschaft Stuttgart', 'magyar-kozosseg', 'Német-magyar társaság', 'Stuttgart', 'Német-magyar társaság · Stuttgart · dug-stuttgart.de', '["Magyar"]', 48.7758, 9.1829, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'BW');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-deutsch-ungarische-gesellschaft-pforzheim-enzkreis', 'Deutsch-Ungarische Gesellschaft Pforzheim-Enzkreis', 'magyar-kozosseg', 'Német-magyar társaság', 'Pforzheim', 'Német-magyar társaság · Pforzheim', '["Magyar"]', 48.8922, 8.6946, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'BW');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-baden-wurttembergi-konzuli-magyar-iskola-es-ovoda', 'Baden-Württembergi Konzuli Magyar Iskola és Óvoda', 'magyar-kozosseg', 'Iskola / óvoda', 'Stuttgart', 'Magyar iskola / óvoda · Stuttgart · bwkmi.ulbe.org', '["Magyar"]', 48.7758, 9.1829, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'BW');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-manoka-magyar-kulturalis-egyesulet', 'MANOKA Magyar Kulturális Egyesület', 'magyar-kozosseg', 'Kultúra / oktatás', 'Karlsruhe', 'Magyar kultúra / oktatás · Karlsruhe', '["Magyar"]', 49.0069, 8.4037, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'BW');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-magyarorszag-stuttgarti-fokonzulatusa', 'Magyarország Stuttgarti Főkonzulátusa', 'magyar-kozosseg', 'Főkonzulátus', 'Stuttgart', 'Magyar főkonzulátus · Stuttgart · stuttgart.mfa.gov.hu', '["Magyar"]', 48.7758, 9.1829, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'BW');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-magyar-katolikus-misszio-munchen', 'Magyar Katolikus Misszió München', 'magyar-kozosseg', 'Egyház', 'München', 'Magyar egyház · München · www.ungarische-mission.de', '["Magyar"]', 48.1351, 11.582, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'BY');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-szent-laszlo-magyar-katolikus-misszio-augsburg', 'Szent László Magyar Katolikus Misszió Augsburg', 'magyar-kozosseg', 'Egyház', 'Augsburg', 'Magyar egyház · Augsburg · augsburgi-katolikusok.de', '["Magyar"]', 48.3705, 10.8978, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'BY');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-deutsch-ungarische-gesellschaft-munchen', 'Deutsch-Ungarische Gesellschaft München', 'magyar-kozosseg', 'Német-magyar társaság', 'München', 'Német-magyar társaság · München', '["Magyar"]', 48.1351, 11.582, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'BY');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-bajororszagi-konzuli-magyar-iskola', 'Bajorországi Konzuli Magyar Iskola', 'magyar-kozosseg', 'Iskola', 'München', 'Magyar iskola · München', '["Magyar"]', 48.1351, 11.582, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'BY');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-magyarorszag-muncheni-fokonzulatusa', 'Magyarország Müncheni Főkonzulátusa', 'magyar-kozosseg', 'Főkonzulátus', 'München', 'Magyar főkonzulátus · München · munchen.mfa.gov.hu', '["Magyar"]', 48.1351, 11.582, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'BY');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-collegium-hungaricum-berlin-liszt-intezet', 'Collegium Hungaricum Berlin (Liszt Intézet)', 'magyar-kozosseg', 'Kulturális intézet', 'Berlin', 'Magyar kulturális intézet · Berlin · culture.hu/de/berlin', '["Magyar"]', 52.52, 13.405, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'BE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-buod-nemetorszagi-magyar-szervezetek-szovetsege', 'BUOD – Németországi Magyar Szervezetek Szövetsége', 'magyar-kozosseg', 'Ernyőszervezet', 'Frankfurt am Main', 'Magyar ernyőszervezet · Frankfurt am Main · buod.de', '["Magyar"]', 50.1109, 8.6821, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'HE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-lingua-hungarica-magyar-hetvegi-iskola-frankfurt', 'Lingua Hungarica – Magyar Hétvégi Iskola Frankfurt', 'magyar-kozosseg', 'Iskola', 'Frankfurt am Main', 'Magyar iskola · Frankfurt am Main', '["Magyar"]', 50.1109, 8.6821, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'HE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-deutsch-ungarische-gesellschaft-frankfurt', 'Deutsch-Ungarische Gesellschaft Frankfurt', 'magyar-kozosseg', 'Német-magyar társaság', 'Frankfurt am Main', 'Német-magyar társaság · Frankfurt am Main', '["Magyar"]', 50.1109, 8.6821, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'HE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-deutsch-ungarische-gesellschaft-darmstadt', 'Deutsch-Ungarische Gesellschaft Darmstadt', 'magyar-kozosseg', 'Német-magyar társaság', 'Darmstadt', 'Német-magyar társaság · Darmstadt', '["Magyar"]', 49.8728, 8.6512, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'HE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-deutsch-ungarische-gesellschaft-hannover', 'Deutsch-Ungarische Gesellschaft Hannover', 'magyar-kozosseg', 'Német-magyar társaság', 'Hannover', 'Német-magyar társaság · Hannover', '["Magyar"]', 52.3759, 9.732, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'NI');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-magyarorszag-dusseldorfi-fokonzulatusa', 'Magyarország Düsseldorfi Főkonzulátusa', 'magyar-kozosseg', 'Főkonzulátus', 'Düsseldorf', 'Magyar főkonzulátus · Düsseldorf · dusseldorf.mfa.gov.hu', '["Magyar"]', 51.2277, 6.7735, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'NW');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-ungarnzentrum-koln-magyar-kozpont', 'Ungarnzentrum Köln – Magyar Központ', 'magyar-kozosseg', 'Közösségi központ', 'Köln', 'Magyar közösségi központ · Köln · ungarnzentrum.de', '["Magyar"]', 50.9375, 6.9603, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'NW');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-eszak-rajna-vesztfaliai-magyar-protestans-gyulekezet', 'Észak-Rajna-Vesztfáliai Magyar Protestáns Gyülekezet', 'magyar-kozosseg', 'Egyház', 'Köln', 'Magyar egyház · Köln · ungarische-gemeinde.de', '["Magyar"]', 50.9375, 6.9603, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'NW');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-deutsch-ungarische-gesellschaft-munster', 'Deutsch-Ungarische Gesellschaft Münster', 'magyar-kozosseg', 'Német-magyar társaság', 'Münster', 'Német-magyar társaság · Münster', '["Magyar"]', 51.9607, 7.6261, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'NW');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-deutsch-ungarische-gesellschaft-kiel', 'Deutsch-Ungarische Gesellschaft Kiel', 'magyar-kozosseg', 'Német-magyar társaság', 'Kiel', 'Német-magyar társaság · Kiel', '["Magyar"]', 54.3233, 10.1228, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'SH');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-ungarisch-sachsischer-kulturverein-neustadt-e-v', 'Ungarisch-Sächsischer Kulturverein Neustadt e.V.', 'magyar-kozosseg', 'Kultúra', 'Neustadt in Sachsen', 'Magyar kultúra · Neustadt in Sachsen', '["Magyar"]', 51.0237, 14.2139, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'SN');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-magyar-klub-dresden', 'Magyar Klub Dresden', 'magyar-kozosseg', 'Klub / közösség', 'Dresden', 'Magyar klub / közösség · Dresden', '["Magyar"]', 51.0504, 13.7373, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'SN');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-hamburgi-magyarok-kozossege', 'Hamburgi Magyarok Közössége', 'magyar-kozosseg', 'Közösség', 'Hamburg', 'Magyar közösség · Hamburg · hamburgi-magyarok.com', '["Magyar"]', 53.5511, 9.9937, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-de-org', 'DE', 'HH');
