-- db/seed-dach-biz.sql — AUTOGENERÁLT (scripts/gen-dach-biz-seed.mjs). NE szerkeszd kézzel.
-- Valódi magyar vendéglátóhelyek/üzletek DACH-ban, per-cég kategóriával. Alkalmazás:
--   wrangler d1 execute kinti-db --remote --file=./db/seed-dach-biz.sql

INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-biz-piroschka', 'Piroschka', 'etterem', 'Étterem', 'Wien', 'Étterem · Wien · www.piroschka.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-biz', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-biz-ilona-stuberl', 'Ilona Stüberl', 'etterem', 'Étterem', 'Wien', 'Étterem · Wien · www.ilonastueberl.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-biz', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('at-biz-budapest-bistro', 'Budapest Bistro', 'etterem', 'Étterem / reggeliző', 'Wien', 'Étterem / reggeliző · Wien · budapestbistro.at', '["Magyar"]', 48.2082, 16.3738, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-biz', 'AT', 'W');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-biz-ungarische-gaststatte-berlin', 'Ungarische Gaststätte Berlin', 'etterem', 'Étterem', 'Berlin', 'Étterem · Berlin · www.ungarische-gaststaette.de', '["Magyar"]', 52.52, 13.405, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-biz', 'DE', 'BE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-biz-zum-ziehbrunnen-ungarisches-restaurant', 'Zum Ziehbrunnen – Ungarisches Restaurant', 'etterem', 'Étterem / hotel', 'Berlin', 'Étterem / hotel · Berlin · zumziehbrunnen.de', '["Magyar"]', 52.52, 13.405, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-biz', 'DE', 'BE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-biz-szimpla-berlin', 'Szimpla Berlin', 'etterem', 'Kávézó / bisztró', 'Berlin', 'Kávézó / bisztró · Berlin · www.szimpla.de', '["Magyar"]', 52.52, 13.405, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-biz', 'DE', 'BE');
INSERT OR IGNORE INTO businesses (id, name, category_id, category_label, address, blurb, languages, lat, lng, pin_x, pin_y, rating, reviews, featured, open_now, moderation_status, claimed, hidden, source, country_code, canton_code) VALUES ('de-biz-budapest-restaurant-munchen', 'Budapest Restaurant München', 'etterem', 'Étterem', 'München', 'Étterem · München · budapest-restaurant.hupont.hu', '["Magyar"]', 48.1351, 11.582, 50, 50, 0, 0, 0, 0, 1, 0, 0, 'seed-biz', 'DE', 'BY');
