-- db/seed-hun-pop-ch.sql — AUTOGENERÁLT (harvest-hun-population-ch.mjs + rögzített élő BFS-lekérdezés). NE szerkeszd kézzel.
-- Forrás: BFS (Bundesamt für Statistik) STATPOP, PX-Web API, tábla px-x-0102010000_104, 2024.
-- Élesítés: wrangler d1 execute kinti-db --remote --file=./db/seed-hun-pop-ch.sql

INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-zh-2024', 'CH', 'ZH', 'Zürich', 'canton', 7344, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-be-2024', 'CH', 'BE', 'Bern', 'canton', 2461, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-lu-2024', 'CH', 'LU', 'Luzern', 'canton', 1829, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-ur-2024', 'CH', 'UR', 'Uri', 'canton', 159, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-sz-2024', 'CH', 'SZ', 'Schwyz', 'canton', 796, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-ow-2024', 'CH', 'OW', 'Obwalden', 'canton', 112, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-nw-2024', 'CH', 'NW', 'Nidwalden', 'canton', 148, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-gl-2024', 'CH', 'GL', 'Glarus', 'canton', 154, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-zg-2024', 'CH', 'ZG', 'Zug', 'canton', 629, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-fr-2024', 'CH', 'FR', 'Freiburg', 'canton', 379, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-so-2024', 'CH', 'SO', 'Solothurn', 'canton', 1495, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-bs-2024', 'CH', 'BS', 'Basel-Stadt', 'canton', 872, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-bl-2024', 'CH', 'BL', 'Basel-Landschaft', 'canton', 1178, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-sh-2024', 'CH', 'SH', 'Schaffhausen', 'canton', 380, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-ar-2024', 'CH', 'AR', 'Appenzell Ausserrhoden', 'canton', 178, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-ai-2024', 'CH', 'AI', 'Appenzell Innerrhoden', 'canton', 25, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-sg-2024', 'CH', 'SG', 'St. Gallen', 'canton', 3434, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-gr-2024', 'CH', 'GR', 'Graubünden', 'canton', 782, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-ag-2024', 'CH', 'AG', 'Aargau', 'canton', 3610, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-tg-2024', 'CH', 'TG', 'Thurgau', 'canton', 2664, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-ti-2024', 'CH', 'TI', 'Ticino', 'canton', 266, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-vd-2024', 'CH', 'VD', 'Vaud', 'canton', 811, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-vs-2024', 'CH', 'VS', 'Valais', 'canton', 492, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-ne-2024', 'CH', 'NE', 'Neuchâtel', 'canton', 73, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-ge-2024', 'CH', 'GE', 'Genève', 'canton', 751, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
INSERT INTO hungarian_population_stats (id, country_code, region_code, region_name, region_level, hungarian_count, year, source, source_url) VALUES ('ch-ju-2024', 'CH', 'JU', 'Jura', 'canton', 18, 2024, 'BFS STATPOP', 'https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/erhebungen/statpop.html') ON CONFLICT(id) DO UPDATE SET hungarian_count=excluded.hungarian_count, updated_at=datetime('now');
