-- ===========================================================================
-- Kinti — seed (a prototípus kinti-data.jsx valós mock adatai).
-- Alkalmazás:  npm run db:seed:local   /   npm run db:seed:remote
-- Újrafuttatható: előbb törlés (gyerek → szülő), majd beszúrás (szülő → gyerek).
-- ===========================================================================
PRAGMA foreign_keys = ON;

DELETE FROM business_daily_views;
DELETE FROM business_stats;
DELETE FROM events;
DELETE FROM businesses;
DELETE FROM categories;

-- --- 1) Kategóriák -------------------------------------------------------------
INSERT INTO categories (id, label, glyph, sort_order) VALUES
  ('all', 'Mind', '⯐', 0),
  ('takaritas_ipari', 'Ablak- / Ipari tisztítás', '🧼', 1),
  ('takaritas_ablak', 'Ablaktisztító / Magaslati', '🧼', 2),
  ('adatvedelmi_tisztviselo', 'Adatvédelmi tisztviselő', '🔒', 3),
  ('adotanacsado', 'Adótanácsadó', '📈', 4),
  ('akupunktura', 'Akupunktúra', '📍', 5),
  ('eskuvoi_fodrasz', 'Alkalmi fodrász / Sminkes', '💄', 6),
  ('allat', 'Állatgondozás', '🐾', 7),
  ('allatorvos', 'Állatorvos', '🐱', 8),
  ('allatpanzio', 'Állatpanzió / Pet Sitting', '🐾', 9),
  ('allatszallito', 'Állatszállítás', '🐕', 10),
  ('allvanyozo', 'Állványozó', '🏗️', 11),
  ('fuggesztett_menyezet', 'Álmennyezet / Gipszkarton', '🏗️', 12),
  ('antik', 'Antikvitás', '🏺', 13),
  ('arnyekolastechnika', 'Árnyékolástechnika / Redőny', '⛱️', 14),
  ('aromaterapia', 'Aromaterapeuta', '🌸', 15),
  ('asztalos', 'Asztalos', '🪚', 16),
  ('autoalkatresz', 'Autóalkatrész / Bontó', '⚙️', 17),
  ('autoberles', 'Autóbérlés / Kozmetika', '🚗', 18),
  ('autofenyezo', 'Autófényező', '🎨', 19),
  ('autokozmetika', 'Autókozmetika', '✨', 20),
  ('gepijarmu_oktato', 'Autósiskola / Oktató', '🚗', 21),
  ('autoszer', 'Autószerelő', '⚙', 22),
  ('autovillamossag', 'Autóvillamosság', '⚡', 23),
  ('badoogos', 'Bádogos', '🛠️', 24),
  ('banki_ugyintezo', 'Banki ügyintéző', '🏦', 25),
  ('beruhazasi_tanacsado', 'Befektetési tanácsadó', '💹', 26),
  ('belgyogyasz', 'Belgyógyász', '🩺', 27),
  ('lakberendezes', 'Belsőépítészet', '🛋️', 28),
  ('bio', 'Biobolt', '🌿', 29),
  ('biztonsagi_or', 'Biztonsági őr / Portás', '🛡️', 30),
  ('biztonsag', 'Biztonságtechnika', '🛡️', 31),
  ('biztositas', 'Biztosítás', '🛡️', 32),
  ('alkusz', 'Biztosítási alkusz', '🛡️', 33),
  ('bontoipar', 'Bontás / Sittszállítás', '🚜', 34),
  ('borbar', 'Borbár / Borkereskedés', '🍷', 35),
  ('borgyogyasz', 'Bőrgyógyász', '🩺', 36),
  ('burkolo', 'Burkoló / Csempéző', '🧱', 37),
  ('busszal', 'Buszos utazás', '🚌', 38),
  ('catering', 'Catering', '🍽️', 39),
  ('tanacsadas', 'Cégalapítás / Tanácsadás', '💼', 40),
  ('ceremoniamester', 'Ceremóniamester / Vőfély', '🎤', 41),
  ('cipesz', 'Cipész / Kulcsmásoló', '🥾', 42),
  ('cukrasz', 'Cukrász / Torták', '🎂', 43),
  ('csaladallitas', 'Családállítás / Pszichodráma', '👥', 44),
  ('csontkovacs', 'Csontkovács / Kiropraktőr', '🦴', 45),
  ('daruvezeto', 'Daru / Nehézgép kezelő', '🏗️', 46),
  ('dekorator', 'Dekoráció / Virágdísz', '🌸', 47),
  ('dietetikus', 'Dietetikus / Táplálkozás', '🍏', 48),
  ('drone_pilot', 'Drónpilóta / Légi felvétel', '🚁', 49),
  ('edzo', 'Edző / Fitness', '💪', 50),
  ('ekszer', 'Ékszerész / Órás', '⌚', 51),
  ('ev_mernok', 'Energetikai szakértő', '⚡', 52),
  ('epitesz', 'Építész / Tervező', '📐', 53),
  ('epitoipar', 'Építőipar', '🔨', 54),
  ('epuletgepeszet', 'Épületgépész', '🔧', 55),
  ('ergoterapeuta', 'Ergoterapeuta', '🏥', 56),
  ('eskuvoi_fotografus', 'Esküvői fotós / Videós', '📸', 57),
  ('eskuvoi_torta', 'Esküvői torta', '🎂', 58),
  ('etterem', 'Étterem', '◍', 59),
  ('fakivago', 'Fakivágás / Kertgondozás', '🪓', 60),
  ('fazekas', 'Fazekas / Keramikus', '🏺', 61),
  ('fejleszto_pedagogus', 'Fejlesztőpedagógus', '👶', 62),
  ('korrepetitor', 'Felzárkóztatás / Korrepetálás', '✏️', 63),
  ('festoművesz', 'Festőművész / Képzőművész', '🎨', 64),
  ('fodrasz', 'Fodrász', '✂', 65),
  ('fogorvos', 'Fogorvos', '🦷', 66),
  ('fordito', 'Fordító', 'A', 67),
  ('fotos', 'Fotós / Videós', '📷', 68),
  ('fotovoltaika', 'Fotovoltaika / Napelem szerelő', '☀️', 69),
  ('fül_orr_gege', 'Fül-orr-gégész', '👂', 70),
  ('futar', 'Futárszolgálat', '✉️', 71),
  ('futas', 'Fuvarozás', '🚚', 72),
  ('grafikus', 'Grafikus', '🎨', 73),
  ('gumiszerviz', 'Gumiszerviz', '⭕', 74),
  ('animator_gyerek', 'Gyermekanimáció', '🎈', 75),
  ('animator', 'Gyermekanimátor', '🎈', 76),
  ('babysitter', 'Gyermekfelügyelet', '👶', 77),
  ('gyermekorvos', 'Gyermekorvos', '👶', 78),
  ('gyogyszeresz', 'Gyógyszerész', '💊', 79),
  ('gyogytornasz', 'Gyógytornász', '🏥', 80),
  ('hajomedence', 'Hajó- és medenceépítés', '🏊', 81),
  ('hajos_iskola', 'Hajós iskola / Skipper', '⛵', 82),
  ('halozatepito', 'Hálózatépítő / Telekom', '🌐', 83),
  ('hangmernök', 'Hangmérnök / Stúdió', '🎙️', 84),
  ('hangszerkeszito', 'Hangszerkészítő / Javító', '🎸', 85),
  ('hazaszerkeszto', 'Házmester', '🧹', 86),
  ('hegeszto', 'Hegesztő / Fémszerkezet', '🔥', 87),
  ('husszek', 'Hentes / Húsbolt', '🥩', 88),
  ('hitel', 'Hitelügyintéző', '💰', 89),
  ('homeopata', 'Homeopata', '🌿', 90),
  ('homlokzatszigetelo', 'Homlokzatszigetelő / Dryvit', '🏠', 91),
  ('hospice', 'Hospice / Otthonápolás', '🏥', 92),
  ('hotel_menedzser', 'Hotel / Panzió menedzser', '🏨', 93),
  ('idegenvezeto', 'Idegenvezető', '🗺️', 94),
  ('idosek_otthona', 'Idősgondozás / Beteggondozó', '👵', 95),
  ('it', 'Informatikus', '⌘', 96),
  ('ingatlan', 'Ingatlan', '🏠', 97),
  ('ertekbecslo', 'Ingatlan értékbecslő', '📋', 98),
  ('ingatlan_fejleszto', 'Ingatlanfejlesztő / Beruházó', '🏗️', 99),
  ('ugyvezeto', 'Interim Menedzser / Tanácsadó', '💼', 100),
  ('iparjogvedelmi', 'Iparjogvédelmi / Szabadalmi', '🔒', 101),
  ('takaritas_irodai', 'Irodatakarítás / Office cleaning', '🧹', 102),
  ('joga', 'Jógaoktató', '🧘', 103),
  ('jogtanacsado', 'Jogtanácsadó', '⚖️', 104),
  ('kandalloepites', 'Kandallóépítés / Kályhás', '🔥', 105),
  ('kaputechnika', 'Kaputechnika / Garázskapu', '🚗', 106),
  ('kardiologus', 'Kardiológus', '❤️', 107),
  ('karosszeria', 'Karosszérialakatos', '🛠️', 108),
  ('karpitos', 'Kárpitos', '🧵', 109),
  ('kavez', 'Kávézó / Cukrászda', '☕', 110),
  ('kemenysepro', 'Kéményseprő', '🎩', 111),
  ('kemenytechnika', 'Kéménytechnika / Kazán', '🔥', 112),
  ('kenyer_pekseg', 'Kenyér / Kézműves péksütemény', '🍞', 113),
  ('kerekpar', 'Kerékpárszerviz', '🚲', 114),
  ('kertesz', 'Kertészet', '🌿', 115),
  ('kerttervezo', 'Kerttervező / Tájépítész', '🏡', 116),
  ('keselelo', 'Késélező / Köszörűs', '🔪', 117),
  ('jatekkeszito', 'Kézműves játékok', '🧸', 118),
  ('cybersecurity', 'Kiberbiztonság / IT audit', '🔒', 119),
  ('klima', 'Klíma / Fűtés', '❄️', 120),
  ('koltoztetes', 'Költöztetés', '📦', 121),
  ('kőműves', 'Kőműves / Betonozó', '🧱', 122),
  ('konyveles', 'Könyvelés', '📊', 123),
  ('kozjegyzo', 'Közjegyző', '📜', 124),
  ('kozlekedesi_mernok', 'Közlekedésmérnök', '🚦', 125),
  ('kozossegi_media', 'Közösségi média menedzser', '📱', 126),
  ('kristalygyogyasz', 'Kristályterápia', '💎', 127),
  ('kutyafodrasz', 'Kutyafodrász', '✂️', 128),
  ('kutya_kikepzo', 'Kutyakiképző / Iskola', '🐕', 129),
  ('laboratorium', 'Laboráns / Vérvétel', '🧪', 130),
  ('lakasfelujitas', 'Lakásfelújítás / Kivitelezés', '🔨', 131),
  ('lakatos', 'Lakatos', '🔑', 132),
  ('life_coach', 'Life Coach / Karrier coach', '🧠', 133),
  ('logisztikus', 'Logisztikus / Raktár', '📦', 134),
  ('logopedus', 'Logopédus', '🗣️', 135),
  ('lovas_oktato', 'Lovaglás / Lovasterápia', '🐎', 136),
  ('magannyomozo', 'Magánnyomozó', '🕵️', 137),
  ('manikur', 'Manikűr / Műköröm', '💅', 138),
  ('marketing', 'Marketing / Fotó', '📸', 139),
  ('masszazs', 'Masszázs', '💆', 140),
  ('maganora', 'Matematika / Reál magántanár', '✏️', 141),
  ('mediator', 'Mediátor / Békéltető', '🤝', 142),
  ('mezogazdasag', 'Mezőgazdaság / Farm', '🌾', 143),
  ('modellszak', 'Modell / Hostess ügynökség', '👠', 144),
  ('motor', 'Motorkerékpár szerviz', '🏍️', 145),
  ('motoros_oktato', 'Motoros iskola / Oktató', '🏍️', 146),
  ('munkaero_kozvetito', 'Munkaerő-közvetítő', '🤝', 147),
  ('galeria', 'Művészeti galéria / Tárlat', '🖼️', 148),
  ('napkollektor', 'Napelem / Szolártechnika', '☀️', 149),
  ('solar_technikus', 'Napelem technikus / Szerelő', '☀️', 150),
  ('idegennyelv_tanar', 'Német / Francia nyelvtanár', '🗣️', 151),
  ('epileptologus', 'Neurológus / Ideggyógyász', '🧠', 152),
  ('nogyogyasz', 'Nőgyógyász / Szülész', '🤰', 153),
  ('nonprofitmenedzser', 'Nonprofit menedzser / Vezető', '🤝', 154),
  ('nyelviskola', 'Nyelviskola', '🏫', 155),
  ('nyilaszaros', 'Nyílászáró / Ablak-ajtó', '🪟', 156),
  ('nyomda', 'Nyomda / Grafika', '🖨️', 157),
  ('oktatastechnologus', 'Oktatástechnológus / e-Learning', '💻', 158),
  ('online_marketing', 'Online marketing / PPC kampány', '📱', 159),
  ('ontozorendszer', 'Öntözőrendszer építés', '💦', 160),
  ('ortopediai_muszeresz', 'Ortopédiai műszerész', '🥾', 161),
  ('ortopedus', 'Ortopédorvos / Sebész', '🦴', 162),
  ('orvos', 'Orvos', '＋', 163),
  ('ovodapedagogus', 'Óvónő / Bölcsőde', '🧸', 164),
  ('parkettazas', 'Padlóburkolás / Parkettázás', '🪵', 165),
  ('pályaorientáció', 'Pályaválasztási tanácsadó', '📈', 166),
  ('looveges2', 'Patkolókovács', '🐎', 167),
  ('looveges', 'Patkolókovács / Lógyógyász', '🐎', 168),
  ('pedikur', 'Pedikűr / Lábápolás', '👣', 169),
  ('pek', 'Pék', '◐', 170),
  ('penzmosasellenes', 'Pénzmosás-ellenes (AML)', '🔒', 171),
  ('penzugyi_tanacsado', 'Pénzügyi tanácsadó', '💰', 172),
  ('piackutatas', 'Piackutatás / Market Research', '📊', 173),
  ('repulo_oktatas', 'Pilótaoktatás / Repülés', '✈️', 174),
  ('projektmenedzser', 'Projektmenedzser (PM)', '📋', 175),
  ('pszichiater', 'Pszichiáter', '🧠', 176),
  ('pszichologus', 'Pszichológus / Coach', '🧠', 177),
  ('pszichoterapia', 'Pszichoterapeuta', '🧠', 178),
  ('rehabilitacios', 'Rehabilitációs szakértő', '🏥', 179),
  ('rendezveny', 'Rendezvényszervezés', '🎉', 180),
  ('rendszergazda', 'Rendszergazda / IT Support', '💻', 181),
  ('sebesz', 'Sebész', '🔪', 182),
  ('seo_szakerto', 'SEO / Keresőoptimalizálás', '📈', 183),
  ('sieles', 'Síoktató', '⛷️', 184),
  ('smink', 'Sminkes / Stylist', '💄', 185),
  ('sportorvos', 'Sportorvos / Sportfizioterápia', '🏃', 186),
  ('talalmanyi_szakerto', 'Szabadalmi / Találmányi ügyvivő', '📜', 187),
  ('forditasszak', 'Szakfordító', '📖', 188),
  ('szallas', 'Szálláshely / Panzió', '🏨', 189),
  ('szallitmanyozo', 'Szállítmányozó / Speditőr', '🚢', 190),
  ('szamviteli_ellenor', 'Számviteli ellenőr / Revisor', '📊', 191),
  ('szaunaepites', 'Szaunaépítés / Wellness', '♨️', 192),
  ('szaunaszeansz', 'Szaunamester', '♨️', 193),
  ('szemelyi_asszisztens', 'Személyi asszisztens', '📅', 194),
  ('szemelyi_edzo', 'Személyi edző', '👟', 195),
  ('szemelyi_stilista', 'Személyi stilista / Imázs', '👗', 196),
  ('szemelyi_vedelem', 'Személyi védelem / Testőr', '🛡️', 197),
  ('szemesz', 'Szemész / Optikus', '👓', 198),
  ('szepseg', 'Szépségápolás', '🌸', 199),
  ('szerkezeti_mernok', 'Szerkezeti mérnök / Statikus', '🏗️', 200),
  ('szinhaz', 'Színház / Színművészet', '🎭', 201),
  ('festo', 'Szobafestő / Tapétázó', '🎨', 202),
  ('szobrasz', 'Szobrász / Kőfaragó', '🗿', 203),
  ('szocialis_munkas', 'Szociális munkás', '🤝', 204),
  ('szocialis_pedagogus', 'Szociálpedagógus', '👥', 205),
  ('pilotas_drone2', 'Szociálpedagógus II.', '👥', 206),
  ('szoftverfejleszto', 'Szoftverfejlesztő', '📱', 207),
  ('szolarium', 'Szolárium / Barnulás', '☀️', 208),
  ('szonyegház', 'Szőnyegtisztító / Vegytisztítás', '🧼', 209),
  ('copywriter', 'Szövegíró / Copywriter', '✍️', 210),
  ('szuretes', 'Szüret / Borász', '🍇', 211),
  ('takarito', 'Takarítás', '⦦', 212),
  ('reflexologus', 'Talpreflexológia', '👣', 213),
  ('tanc', 'Tánctanár', '💃', 214),
  ('taxis', 'Taxis / Sofőr', '🚕', 215),
  ('temetkezes', 'Temetkezés', '⚱️', 216),
  ('sportorvos2', 'Terápiás úszás / Hidroterápia', '🏊', 217),
  ('terkovezes', 'Térkövezés / Útépítés', '🧱', 218),
  ('termeszetgyogyasz', 'Természetgyógyász', '🌱', 219),
  ('tetofedo', 'Tetőfedő / Ács', '🏠', 220),
  ('tetovalas', 'Tetoválóművész', '🖋️', 221),
  ('tisztito', 'Tisztító / Ruhavarró', '👔', 222),
  ('nemet_tolmacs', 'Tolmács / Konferenciatolmács', '🗣️', 223),
  ('ugyfelszolgalat', 'Ügyfélszolgálat / VA', '📞', 224),
  ('ugyved', 'Ügyvéd', '§', 225),
  ('urologus', 'Urológus', '🩺', 226),
  ('uszas', 'Úszásoktatás', '🏊', 227),
  ('uveges', 'Üveges', '💎', 228),
  ('vagyonvedelem', 'Vagyonvédelmi szakértő', '🛡️', 229),
  ('vallalkozoi_coach', 'Vállalkozói coach / Startup mentor', '💼', 230),
  ('vamugyintezo', 'Vámügyintéző', '🛂', 231),
  ('varrono', 'Varrónő', '🧵', 232),
  ('videovago', 'Videóvágó / YouTube', '🎬', 233),
  ('villamvedelem', 'Villámvédelem', '⚡', 234),
  ('villany', 'Villanyszerelő', '⚡', 235),
  ('virag', 'Virágüzlet', '💐', 236),
  ('virtuális_asszisztens', 'Virtuális Asszisztens', '💻', 237),
  ('szigetelo', 'Víz- és hőszigetelő', '💧', 238),
  ('gazvez', 'Víz-gáz szerelő', '💧', 239),
  ('zenesz', 'Zene / Zenetanár', '🎵', 240),
  ('zenetermelo', 'Zenei producer / Hangstúdió', '🎚️', 241),
  ('zenekar', 'Zenekar / Party DJ', '🎵', 242),
  ('zoldseges', 'Zöldséges / Hofladen', '🍎', 243);

-- --- 3) Vállalkozások ----------------------------------------------------------
-- A lat/lng a Zürichi városrészek tényleges utcáihoz illesztett, plauzibilis
-- WGS84 koordináta (OpenStreetMap-en ellenőrizhető). A pin_x/pin_y a régi
-- prototípus mockupjához tartozik (0–100 %), a térkép a lat/lng-t használja.
INSERT INTO businesses
  (id, name, category_id, category_label, rating, reviews, dist_text, dist_meters,
   address, phone, pin_x, pin_y, lat, lng, featured, blurb, open_now, open_text, years_here,
   languages, photo, accent_photo, owner_user_id)
VALUES
  ('kovacs-anna', 'Kovács Anna fodrászat', 'fodrasz', 'Fodrász',
   4.9, 47, '4 perc', 320,
   'Birmensdorferstrasse 142, 8003 Zürich', '+41 76 421 88 03', 53, 49,
   47.36750, 8.51690, 1,
   'Magyar fodrász Wiedikonban. Női és férfi vágás, festés, melír. Magyarul, gyorsan, házias hangulatban.',
   1, 'Nyitva · zár 19:00-kor', 6,
   '["Magyar","Deutsch","English"]',
   'linear-gradient(135deg, #d6b89a 0%, #b48868 60%, #8c5e3c 100%)',
   'linear-gradient(135deg, #e8d4b8, #c89a76)',
   NULL),

  ('horvath-auto', 'Horváth autószerviz', 'autoszer', 'Autószerelő',
   4.8, 112, '11 perc', 850,
   'Letzigraben 89, 8003 Zürich', '+41 79 304 12 55', 36, 38,
   47.38260, 8.50630, 0,
   'Minden márka. Magyarul beszélünk. Becsületes ár, gyors átfutás.',
   1, 'Nyitva · zár 18:00-kor', NULL,
   NULL,
   'linear-gradient(135deg, #5c6d63 0%, #2e3f33 100%)',
   NULL,
   NULL),

  ('dr-szabo', 'Dr. Szabó Eszter – fogorvos', 'orvos', 'Fogorvos',
   5.0, 28, '7 perc', 520,
   'Seebahnstrasse 231, 8004 Zürich', '+41 44 555 12 99', 58, 62,
   47.37130, 8.52150, 1,
   'Általános és gyermek fogászat. Krankenkasse-elszámolás, magyar nyelvű konzultáció.',
   0, 'Zárva · nyit 8:00-kor', NULL,
   NULL,
   'linear-gradient(135deg, #e9d8c0 0%, #c8392e 100%)',
   NULL,
   NULL),

  ('nagy-pek', 'Nagy pékség', 'pek', 'Pék',
   4.7, 89, '6 perc', 430,
   'Albisriederplatz 4, 8003 Zürich', '+41 43 211 06 02', 44, 55,
   47.37870, 8.50630, 0,
   'Igazi magyar kenyér, kifli, pogácsa minden reggel. Szombaton bejgli is.',
   1, 'Nyitva · zár 17:00-kor', NULL,
   NULL,
   'linear-gradient(135deg, #f0d9b5 0%, #c89a5c 100%)',
   NULL,
   NULL),

  ('molnar-ugyved', 'Molnár & Partner ügyvédi iroda', 'ugyved', 'Ügyvéd',
   4.9, 23, '14 perc', 1100,
   'Bahnhofstrasse 88, 8001 Zürich', '+41 44 200 55 00', 68, 32,
   47.37330, 8.53920, 0,
   'Munkajog, családjog, tartózkodás. Svájci és magyar jogban is otthon.',
   1, 'Nyitva · zár 18:00-kor', NULL,
   NULL,
   'linear-gradient(135deg, #1d4434 0%, #0e1f17 100%)',
   NULL,
   NULL),

  ('kis-kocsma', 'Kiskocsma – magyar étterem', 'etterem', 'Étterem',
   4.6, 203, '9 perc', 720,
   'Langstrasse 152, 8004 Zürich', '+41 44 271 33 11', 60, 44,
   47.37920, 8.53160, 0,
   'Gulyás, töltött káposzta, rétes. Magyar borok. Csütörtök este élőzene.',
   1, 'Nyitva · zár 23:00-kor', NULL,
   NULL,
   'linear-gradient(135deg, #c8392e 0%, #6b1d18 100%)',
   NULL,
   NULL),

  ('toth-villany', 'Tóth villanyszerelő', 'villany', 'Villanyszerelő',
   4.8, 56, '15 perc', 1200,
   'Hardturmstrasse 11, 8005 Zürich', NULL, 30, 22,
   47.38950, 8.51680, 0,
   'Lakásfelújítás, hibakeresés, smart-home. 24/7 vészhelyzet.',
   1, 'Nyitva · 24/7', NULL,
   NULL,
   'linear-gradient(135deg, #f0c14a 0%, #8c5e1a 100%)',
   NULL,
   NULL);

-- --- 4) Események --------------------------------------------------------------
INSERT INTO events
  (id, title, event_date, date_day, date_month, date_weekday, start_time, venue, going, tag, color)
VALUES
  ('bal',      'Zürichi Magyar Bál 2026',          '2026-11-14', '14', 'NOV', 'szombat',   '19:00', 'Volkshaus, Helvetiaplatz', 187, 'Kulturális', '#c8392e'),
  ('piknik',   'Magyar piknik a Sihl-parton',      '2026-06-07', '07', 'JÚN', 'vasárnap',  '11:00', 'Sihl-part, Allmend',        64, 'Család',     '#1d4434'),
  ('foci',     'Magyar–Sváb focimeccs',            '2026-06-22', '22', 'JÚN', 'vasárnap',  '15:30', 'Sportplatz Hardhof',        31, 'Sport',      '#1d4434'),
  ('irodalmi', 'Magyar irodalmi est – Esterházy',  '2026-07-03', '03', 'JÚL', 'csütörtök', '19:30', 'Kafi Schoffel',             22, 'Kulturális', '#c8392e');

-- --- 6) Dashboard heti KPI (Kovács Anna fodrászat) -----------------------------
INSERT INTO business_stats
  (business_id, week_views, week_views_delta, week_clicks, week_clicks_delta, week_calls, week_calls_delta)
VALUES
  ('kovacs-anna', 248, '+34%', 71, '+22%', 19, '+58%');

-- --- 7) Dashboard 14 napos trendvonal (megtekintések) --------------------------
--    A prototípus chart tömbje: [12,18,15,22,19,28,24,31,27,35,38,42,51,48]
--    14 nap, a legutolsó a legfrissebb (összeg = 410, lásd "14 NAP · +41%").
INSERT INTO business_daily_views (business_id, stat_date, views) VALUES
  ('kovacs-anna', '2026-05-12', 12),
  ('kovacs-anna', '2026-05-13', 18),
  ('kovacs-anna', '2026-05-14', 15),
  ('kovacs-anna', '2026-05-15', 22),
  ('kovacs-anna', '2026-05-16', 19),
  ('kovacs-anna', '2026-05-17', 28),
  ('kovacs-anna', '2026-05-18', 24),
  ('kovacs-anna', '2026-05-19', 31),
  ('kovacs-anna', '2026-05-20', 27),
  ('kovacs-anna', '2026-05-21', 35),
  ('kovacs-anna', '2026-05-22', 38),
  ('kovacs-anna', '2026-05-23', 42),
  ('kovacs-anna', '2026-05-24', 51),
  ('kovacs-anna', '2026-05-25', 48);
