INSERT INTO categories (id, label, glyph, sort_order) VALUES
  ('all', 'Mind', 'Ô»É', 0),
  ('takaritas_ipari', 'Ablak- / Ipari tiszt├şt├ís', '­čž╝', 1),
  ('takaritas_ablak', 'Ablaktiszt├şt├│ / Magaslati', '­čž╝', 2),
  ('adatvedelmi_tisztviselo', 'Adatv├ędelmi tisztvisel┼Ĺ', '­čöĺ', 3),
  ('adotanacsado', 'Ad├│tan├ícsad├│', '­čôł', 4),
  ('akupunktura', 'Akupunkt├║ra', '­čôŹ', 5),
  ('eskuvoi_fodrasz', 'Alkalmi fodr├ísz / Sminkes', '­čĺä', 6),
  ('allat', '├üllatgondoz├ís', '­čÉż', 7),
  ('allatorvos', '├üllatorvos', '­čÉ▒', 8),
  ('allatpanzio', '├üllatpanzi├│ / Pet Sitting', '­čÉż', 9),
  ('allatszallito', '├üllatsz├íll├şt├ís', '­čÉĽ', 10),
  ('allvanyozo', '├üllv├ínyoz├│', '­čĆŚ´ŞĆ', 11),
  ('fuggesztett_menyezet', '├ülmennyezet / Gipszkarton', '­čĆŚ´ŞĆ', 12),
  ('antik', 'Antikvit├ís', '­čĆ║', 13),
  ('arnyekolastechnika', '├ürny├ękol├ístechnika / Red┼Ĺny', 'ÔŤ▒´ŞĆ', 14),
  ('aromaterapia', 'Aromaterapeuta', '­čîŞ', 15),
  ('asztalos', 'Asztalos', '­č¬Ü', 16),
  ('autoalkatresz', 'Aut├│alkatr├ęsz / Bont├│', 'ÔÜÖ´ŞĆ', 17),
  ('autoberles', 'Aut├│b├ęrl├ęs / Kozmetika', '­čÜŚ', 18),
  ('autofenyezo', 'Aut├│f├ęnyez┼Ĺ', '­čÄĘ', 19),
  ('autokozmetika', 'Aut├│kozmetika', 'ÔťĘ', 20),
  ('gepijarmu_oktato', 'Aut├│siskola / Oktat├│', '­čÜŚ', 21),
  ('autoszer', 'Aut├│szerel┼Ĺ', 'ÔÜÖ', 22),
  ('autovillamossag', 'Aut├│villamoss├íg', 'ÔÜí', 23),
  ('badoogos', 'B├ídogos', '­čŤá´ŞĆ', 24),
  ('banki_ugyintezo', 'Banki ├╝gyint├ęz┼Ĺ', '­čĆŽ', 25),
  ('beruhazasi_tanacsado', 'Befektet├ęsi tan├ícsad├│', '­čĺ╣', 26),
  ('belgyogyasz', 'Belgy├│gy├ísz', '­čę║', 27),
  ('lakberendezes', 'Bels┼Ĺ├ęp├şt├ęszet', '­čŤő´ŞĆ', 28),
  ('bio', 'Biobolt', '­čî┐', 29),
  ('biztonsagi_or', 'Biztons├ígi ┼Ĺr / Port├ís', '­čŤí´ŞĆ', 30),
  ('biztonsag', 'Biztons├ígtechnika', '­čŤí´ŞĆ', 31),
  ('biztositas', 'Biztos├şt├ís', '­čŤí´ŞĆ', 32),
  ('alkusz', 'Biztos├şt├ísi alkusz', '­čŤí´ŞĆ', 33),
  ('bontoipar', 'Bont├ís / Sittsz├íll├şt├ís', '­čÜť', 34),
  ('borbar', 'Borb├ír / Borkeresked├ęs', '­čŹĚ', 35),
  ('borgyogyasz', 'B┼Ĺrgy├│gy├ísz', '­čę║', 36),
  ('burkolo', 'Burkol├│ / Csemp├ęz┼Ĺ', '­čž▒', 37),
  ('busszal', 'Buszos utaz├ís', '­čÜî', 38),
  ('catering', 'Catering', '­čŹŻ´ŞĆ', 39),
  ('tanacsadas', 'C├ęgalap├şt├ís / Tan├ícsad├ís', '­čĺ╝', 40),
  ('ceremoniamester', 'Cerem├│niamester / V┼Ĺf├ęly', '­čÄĄ', 41),
  ('cipesz', 'Cip├ęsz / Kulcsm├ísol├│', '­čąż', 42),
  ('cukrasz', 'Cukr├ísz / Tort├ík', '­čÄé', 43),
  ('csaladallitas', 'Csal├íd├íll├şt├ís / Pszichodr├íma', '­čĹą', 44),
  ('csontkovacs', 'Csontkov├ícs / Kiroprakt┼Ĺr', '­čŽ┤', 45),
  ('daruvezeto', 'Daru / Neh├ęzg├ęp kezel┼Ĺ', '­čĆŚ´ŞĆ', 46),
  ('dekorator', 'Dekor├íci├│ / Vir├ígd├şsz', '­čîŞ', 47),
  ('dietetikus', 'Dietetikus / T├ípl├ílkoz├ís', '­čŹĆ', 48),
  ('drone_pilot', 'Dr├│npil├│ta / L├ęgi felv├ętel', '­čÜü', 49),
  ('edzo', 'Edz┼Ĺ / Fitness', '­čĺ¬', 50),
  ('ekszer', '├ëkszer├ęsz / ├ôr├ís', 'ÔîÜ', 51),
  ('ev_mernok', 'Energetikai szak├ęrt┼Ĺ', 'ÔÜí', 52),
  ('epitesz', '├ëp├şt├ęsz / Tervez┼Ĺ', '­čôÉ', 53),
  ('epitoipar', '├ëp├şt┼Ĺipar', '­čöĘ', 54),
  ('epuletgepeszet', '├ëp├╝letg├ęp├ęsz', '­čöž', 55),
  ('ergoterapeuta', 'Ergoterapeuta', '­čĆą', 56),
  ('eskuvoi_fotografus', 'Esk├╝v┼Ĺi fot├│s / Vide├│s', '­čôŞ', 57),
  ('eskuvoi_torta', 'Esk├╝v┼Ĺi torta', '­čÄé', 58),
  ('etterem', '├ëtterem', 'ÔŚŹ', 59),
  ('fakivago', 'Fakiv├íg├ís / Kertgondoz├ís', '­č¬ô', 60),
  ('fazekas', 'Fazekas / Keramikus', '­čĆ║', 61),
  ('fejleszto_pedagogus', 'Fejleszt┼Ĺpedag├│gus', '­čĹÂ', 62),
  ('korrepetitor', 'Felz├írk├│ztat├ís / Korrepet├íl├ís', 'ÔťĆ´ŞĆ', 63),
  ('festom┼▒vesz', 'Fest┼Ĺm┼▒v├ęsz / K├ępz┼Ĺm┼▒v├ęsz', '­čÄĘ', 64),
  ('fodrasz', 'Fodr├ísz', 'Ôťé', 65),
  ('fogorvos', 'Fogorvos', '­čŽĚ', 66),
  ('fordito', 'Ford├şt├│', 'A', 67),
  ('fotos', 'Fot├│s / Vide├│s', '­čôĚ', 68),
  ('fotovoltaika', 'Fotovoltaika / Napelem szerel┼Ĺ', 'ÔśÇ´ŞĆ', 69),
  ('f├╝l_orr_gege', 'F├╝l-orr-g├ęg├ęsz', '­čĹé', 70),
  ('futar', 'Fut├írszolg├ílat', 'Ôťë´ŞĆ', 71),
  ('futas', 'Fuvaroz├ís', '­čÜÜ', 72),
  ('grafikus', 'Grafikus', '­čÄĘ', 73),
  ('gumiszerviz', 'Gumiszerviz', 'ÔşĽ', 74),
  ('animator_gyerek', 'Gyermekanim├íci├│', '­čÄł', 75),
  ('animator', 'Gyermekanim├ítor', '­čÄł', 76),
  ('babysitter', 'Gyermekfel├╝gyelet', '­čĹÂ', 77),
  ('gyermekorvos', 'Gyermekorvos', '­čĹÂ', 78),
  ('gyogyszeresz', 'Gy├│gyszer├ęsz', '­čĺŐ', 79),
  ('gyogytornasz', 'Gy├│gytorn├ísz', '­čĆą', 80),
  ('hajomedence', 'Haj├│- ├ęs medence├ęp├şt├ęs', '­čĆŐ', 81),
  ('hajos_iskola', 'Haj├│s iskola / Skipper', 'ÔŤÁ', 82),
  ('halozatepito', 'H├íl├│zat├ęp├şt┼Ĺ / Telekom', '­čîÉ', 83),
  ('hangmern├Âk', 'Hangm├ęrn├Âk / St├║di├│', '­čÄÖ´ŞĆ', 84),
  ('hangszerkeszito', 'Hangszerk├ęsz├şt┼Ĺ / Jav├şt├│', '­čÄŞ', 85),
  ('hazaszerkeszto', 'H├ízmester', '­čž╣', 86),
  ('hegeszto', 'Hegeszt┼Ĺ / F├ęmszerkezet', '­čöą', 87),
  ('husszek', 'Hentes / H├║sbolt', '­čąę', 88),
  ('hitel', 'Hitel├╝gyint├ęz┼Ĺ', '­čĺ░', 89),
  ('homeopata', 'Homeopata', '­čî┐', 90),
  ('homlokzatszigetelo', 'Homlokzatszigetel┼Ĺ / Dryvit', '­čĆá', 91),
  ('hospice', 'Hospice / Otthon├ípol├ís', '­čĆą', 92),
  ('hotel_menedzser', 'Hotel / Panzi├│ menedzser', '­čĆĘ', 93),
  ('idegenvezeto', 'Idegenvezet┼Ĺ', '­čŚ║´ŞĆ', 94),
  ('idosek_otthona', 'Id┼Ĺsgondoz├ís / Beteggondoz├│', '­čĹÁ', 95),
  ('it', 'Informatikus', 'Ôîś', 96),
  ('ingatlan', 'Ingatlan', '­čĆá', 97),
  ('ertekbecslo', 'Ingatlan ├ęrt├ękbecsl┼Ĺ', '­čôő', 98),
  ('ingatlan_fejleszto', 'Ingatlanfejleszt┼Ĺ / Beruh├íz├│', '­čĆŚ´ŞĆ', 99),
  ('ugyvezeto', 'Interim Menedzser / Tan├ícsad├│', '­čĺ╝', 100),
  ('iparjogvedelmi', 'Iparjogv├ędelmi / Szabadalmi', '­čöĺ', 101),
  ('takaritas_irodai', 'Irodatakar├şt├ís / Office cleaning', '­čž╣', 102),
  ('joga', 'J├│gaoktat├│', '­čžś', 103),
  ('jogtanacsado', 'Jogtan├ícsad├│', 'ÔÜľ´ŞĆ', 104),
  ('kandalloepites', 'Kandall├│├ęp├şt├ęs / K├ílyh├ís', '­čöą', 105),
  ('kaputechnika', 'Kaputechnika / Gar├ízskapu', '­čÜŚ', 106),
  ('kardiologus', 'Kardiol├│gus', 'ÔŁĄ´ŞĆ', 107),
  ('karosszeria', 'Karossz├ęrialakatos', '­čŤá´ŞĆ', 108),
  ('karpitos', 'K├írpitos', '­čžÁ', 109),
  ('kavez', 'K├ív├ęz├│ / Cukr├íszda', 'ÔśĽ', 110),
  ('kemenysepro', 'K├ęm├ęnysepr┼Ĺ', '­čÄę', 111),
  ('kemenytechnika', 'K├ęm├ęnytechnika / Kaz├ín', '­čöą', 112),
  ('kenyer_pekseg', 'Keny├ęr / K├ęzm┼▒ves p├ęks├╝tem├ęny', '­čŹ×', 113),
  ('kerekpar', 'Ker├ękp├írszerviz', '­čÜ▓', 114),
  ('kertesz', 'Kert├ęszet', '­čî┐', 115),
  ('kerttervezo', 'Kerttervez┼Ĺ / T├íj├ęp├şt├ęsz', '­čĆí', 116),
  ('keselelo', 'K├ęs├ęlez┼Ĺ / K├Âsz├Âr┼▒s', '­čö¬', 117),
  ('jatekkeszito', 'K├ęzm┼▒ves j├ít├ękok', '­čžŞ', 118),
  ('cybersecurity', 'Kiberbiztons├íg / IT audit', '­čöĺ', 119),
  ('klima', 'Kl├şma / F┼▒t├ęs', 'ÔŁä´ŞĆ', 120),
  ('koltoztetes', 'K├Âlt├Âztet├ęs', '­čôŽ', 121),
  ('k┼Ĺm┼▒ves', 'K┼Ĺm┼▒ves / Betonoz├│', '­čž▒', 122),
  ('konyveles', 'K├Ânyvel├ęs', '­čôŐ', 123),
  ('kozjegyzo', 'K├Âzjegyz┼Ĺ', '­čôť', 124),
  ('kozlekedesi_mernok', 'K├Âzleked├ęsm├ęrn├Âk', '­čÜŽ', 125),
  ('kozossegi_media', 'K├Âz├Âss├ęgi m├ędia menedzser', '­čô▒', 126),
  ('kristalygyogyasz', 'Krist├ílyter├ípia', '­čĺÄ', 127),
  ('kutyafodrasz', 'Kutyafodr├ísz', 'Ôťé´ŞĆ', 128),
  ('kutya_kikepzo', 'Kutyakik├ępz┼Ĺ / Iskola', '­čÉĽ', 129),
  ('laboratorium', 'Labor├íns / V├ęrv├ętel', '­čž¬', 130),
  ('lakasfelujitas', 'Lak├ísfel├║j├şt├ís / Kivitelez├ęs', '­čöĘ', 131),
  ('lakatos', 'Lakatos', '­čöĹ', 132),
  ('life_coach', 'Life Coach / Karrier coach', '­čžá', 133),
  ('logisztikus', 'Logisztikus / Rakt├ír', '­čôŽ', 134),
  ('logopedus', 'Logop├ędus', '­čŚú´ŞĆ', 135),
  ('lovas_oktato', 'Lovagl├ís / Lovaster├ípia', '­čÉÄ', 136),
  ('magannyomozo', 'Mag├ínnyomoz├│', '­čĽÁ´ŞĆ', 137),
  ('manikur', 'Manik┼▒r / M┼▒k├Âr├Âm', '­čĺů', 138),
  ('marketing', 'Marketing / Fot├│', '­čôŞ', 139),
  ('masszazs', 'Massz├ízs', '­čĺć', 140),
  ('maganora', 'Matematika / Re├íl mag├íntan├ír', 'ÔťĆ´ŞĆ', 141),
  ('mediator', 'Medi├ítor / B├ęk├ęltet┼Ĺ', '­čĄŁ', 142),
  ('mezogazdasag', 'Mez┼Ĺgazdas├íg / Farm', '­čîż', 143),
  ('modellszak', 'Modell / Hostess ├╝gyn├Âks├ęg', '­čĹá', 144),
  ('motor', 'Motorker├ękp├ír szerviz', '­čĆŹ´ŞĆ', 145),
  ('motoros_oktato', 'Motoros iskola / Oktat├│', '­čĆŹ´ŞĆ', 146),
  ('munkaero_kozvetito', 'Munkaer┼Ĺ-k├Âzvet├şt┼Ĺ', '­čĄŁ', 147),
  ('galeria', 'M┼▒v├ęszeti gal├ęria / T├írlat', '­čľ╝´ŞĆ', 148),
  ('napkollektor', 'Napelem / Szol├írtechnika', 'ÔśÇ´ŞĆ', 149),
  ('solar_technikus', 'Napelem technikus / Szerel┼Ĺ', 'ÔśÇ´ŞĆ', 150),
  ('idegennyelv_tanar', 'N├ęmet / Francia nyelvtan├ír', '­čŚú´ŞĆ', 151),
  ('epileptologus', 'Neurol├│gus / Ideggy├│gy├ísz', '­čžá', 152),
  ('nogyogyasz', 'N┼Ĺgy├│gy├ísz / Sz├╝l├ęsz', '­čĄ░', 153),
  ('nonprofitmenedzser', 'Nonprofit menedzser / Vezet┼Ĺ', '­čĄŁ', 154),
  ('nyelviskola', 'Nyelviskola', '­čĆź', 155),
  ('nyilaszaros', 'Ny├şl├ísz├ír├│ / Ablak-ajt├│', '­č¬č', 156),
  ('nyomda', 'Nyomda / Grafika', '­čľĘ´ŞĆ', 157),
  ('oktatastechnologus', 'Oktat├ístechnol├│gus / e-Learning', '­čĺ╗', 158),
  ('online_marketing', 'Online marketing / PPC kamp├íny', '­čô▒', 159),
  ('ontozorendszer', '├ľnt├Âz┼Ĺrendszer ├ęp├şt├ęs', '­čĺŽ', 160),
  ('ortopediai_muszeresz', 'Ortop├ędiai m┼▒szer├ęsz', '­čąż', 161),
  ('ortopedus', 'Ortop├ędorvos / Seb├ęsz', '­čŽ┤', 162),
  ('orvos', 'Orvos', '´╝ő', 163),
  ('ovodapedagogus', '├ôv├│n┼Ĺ / B├Âlcs┼Ĺde', '­čžŞ', 164),
  ('parkettazas', 'Padl├│burkol├ís / Parkett├íz├ís', '­č¬Á', 165),
  ('p├ílyaorient├íci├│', 'P├ílyav├ílaszt├ísi tan├ícsad├│', '­čôł', 166),
  ('looveges2', 'Patkol├│kov├ícs', '­čÉÄ', 167),
  ('looveges', 'Patkol├│kov├ícs / L├│gy├│gy├ísz', '­čÉÄ', 168),
  ('pedikur', 'Pedik┼▒r / L├íb├ípol├ís', '­čĹú', 169),
  ('pek', 'P├ęk', 'ÔŚÉ', 170),
  ('penzmosasellenes', 'P├ęnzmos├ís-ellenes (AML)', '­čöĺ', 171),
  ('penzugyi_tanacsado', 'P├ęnz├╝gyi tan├ícsad├│', '­čĺ░', 172),
  ('piackutatas', 'Piackutat├ís / Market Research', '­čôŐ', 173),
  ('repulo_oktatas', 'Pil├│taoktat├ís / Rep├╝l├ęs', 'Ôťł´ŞĆ', 174),
  ('projektmenedzser', 'Projektmenedzser (PM)', '­čôő', 175),
  ('pszichiater', 'Pszichi├íter', '­čžá', 176),
  ('pszichologus', 'Pszichol├│gus / Coach', '­čžá', 177),
  ('pszichoterapia', 'Pszichoterapeuta', '­čžá', 178),
  ('rehabilitacios', 'Rehabilit├íci├│s szak├ęrt┼Ĺ', '­čĆą', 179),
  ('rendezveny', 'Rendezv├ęnyszervez├ęs', '­čÄë', 180),
  ('rendszergazda', 'Rendszergazda / IT Support', '­čĺ╗', 181),
  ('sebesz', 'Seb├ęsz', '­čö¬', 182),
  ('seo_szakerto', 'SEO / Keres┼Ĺoptimaliz├íl├ís', '­čôł', 183),
  ('sieles', 'S├şoktat├│', 'ÔŤĚ´ŞĆ', 184),
  ('smink', 'Sminkes / Stylist', '­čĺä', 185),
  ('sportorvos', 'Sportorvos / Sportfizioter├ípia', '­čĆâ', 186),
  ('talalmanyi_szakerto', 'Szabadalmi / Tal├ílm├ínyi ├╝gyviv┼Ĺ', '­čôť', 187),
  ('forditasszak', 'Szakford├şt├│', '­čôľ', 188),
  ('szallas', 'Sz├íll├íshely / Panzi├│', '­čĆĘ', 189),
  ('szallitmanyozo', 'Sz├íll├ştm├ínyoz├│ / Spedit┼Ĺr', '­čÜó', 190),
  ('szamviteli_ellenor', 'Sz├ímviteli ellen┼Ĺr / Revisor', '­čôŐ', 191),
  ('szaunaepites', 'Szauna├ęp├şt├ęs / Wellness', 'ÔÖĘ´ŞĆ', 192),
  ('szaunaszeansz', 'Szaunamester', 'ÔÖĘ´ŞĆ', 193),
  ('szemelyi_asszisztens', 'Szem├ęlyi asszisztens', '­čôů', 194),
  ('szemelyi_edzo', 'Szem├ęlyi edz┼Ĺ', '­čĹč', 195),
  ('szemelyi_stilista', 'Szem├ęlyi stilista / Im├ízs', '­čĹŚ', 196),
  ('szemelyi_vedelem', 'Szem├ęlyi v├ędelem / Test┼Ĺr', '­čŤí´ŞĆ', 197),
  ('szemesz', 'Szem├ęsz / Optikus', '­čĹô', 198),
  ('szepseg', 'Sz├ęps├ęg├ípol├ís', '­čîŞ', 199),
  ('szerkezeti_mernok', 'Szerkezeti m├ęrn├Âk / Statikus', '­čĆŚ´ŞĆ', 200),
  ('szinhaz', 'Sz├şnh├íz / Sz├şnm┼▒v├ęszet', '­čÄş', 201),
  ('festo', 'Szobafest┼Ĺ / Tap├ęt├íz├│', '­čÄĘ', 202),
  ('szobrasz', 'Szobr├ísz / K┼Ĺfarag├│', '­čŚ┐', 203),
  ('szocialis_munkas', 'Szoci├ílis munk├ís', '­čĄŁ', 204),
  ('szocialis_pedagogus', 'Szoci├ílpedag├│gus', '­čĹą', 205),
  ('pilotas_drone2', 'Szoci├ílpedag├│gus II.', '­čĹą', 206),
  ('szoftverfejleszto', 'Szoftverfejleszt┼Ĺ', '­čô▒', 207),
  ('szolarium', 'Szol├írium / Barnul├ís', 'ÔśÇ´ŞĆ', 208),
  ('szonyegh├íz', 'Sz┼Ĺnyegtiszt├şt├│ / Vegytiszt├şt├ís', '­čž╝', 209),
  ('copywriter', 'Sz├Âveg├şr├│ / Copywriter', 'ÔťŹ´ŞĆ', 210),
  ('szuretes', 'Sz├╝ret / Bor├ísz', '­čŹç', 211),
  ('takarito', 'Takar├şt├ís', 'ÔŽŽ', 212),
  ('reflexologus', 'Talpreflexol├│gia', '­čĹú', 213),
  ('tanc', 'T├ínctan├ír', '­čĺâ', 214),
  ('taxis', 'Taxis / Sof┼Ĺr', '­čÜĽ', 215),
  ('temetkezes', 'Temetkez├ęs', 'ÔÜ▒´ŞĆ', 216),
  ('sportorvos2', 'Ter├ípi├ís ├║sz├ís / Hidroter├ípia', '­čĆŐ', 217),
  ('terkovezes', 'T├ęrk├Âvez├ęs / ├Üt├ęp├şt├ęs', '­čž▒', 218),
  ('termeszetgyogyasz', 'Term├ęszetgy├│gy├ísz', '­čî▒', 219),
  ('tetofedo', 'Tet┼Ĺfed┼Ĺ / ├ücs', '­čĆá', 220),
  ('tetovalas', 'Tetov├íl├│m┼▒v├ęsz', '­čľő´ŞĆ', 221),
  ('tisztito', 'Tiszt├şt├│ / Ruhavarr├│', '­čĹö', 222),
  ('nemet_tolmacs', 'Tolm├ícs / Konferenciatolm├ícs', '­čŚú´ŞĆ', 223),
  ('ugyfelszolgalat', '├ťgyf├ęlszolg├ílat / VA', '­čô×', 224),
  ('ugyved', '├ťgyv├ęd', '┬ž', 225),
  ('urologus', 'Urol├│gus', '­čę║', 226),
  ('uszas', '├Üsz├ísoktat├ís', '­čĆŐ', 227),
  ('uveges', '├ťveges', '­čĺÄ', 228),
  ('vagyonvedelem', 'Vagyonv├ędelmi szak├ęrt┼Ĺ', '­čŤí´ŞĆ', 229),
  ('vallalkozoi_coach', 'V├íllalkoz├│i coach / Startup mentor', '­čĺ╝', 230),
  ('vamugyintezo', 'V├ím├╝gyint├ęz┼Ĺ', '­čŤé', 231),
  ('varrono', 'Varr├│n┼Ĺ', '­čžÁ', 232),
  ('videovago', 'Vide├│v├íg├│ / YouTube', '­čÄČ', 233),
  ('villamvedelem', 'Vill├ímv├ędelem', 'ÔÜí', 234),
  ('villany', 'Villanyszerel┼Ĺ', 'ÔÜí', 235),
  ('virag', 'Vir├íg├╝zlet', '­čĺÉ', 236),
  ('virtu├ílis_asszisztens', 'Virtu├ílis Asszisztens', '­čĺ╗', 237),
  ('szigetelo', 'V├şz- ├ęs h┼Ĺszigetel┼Ĺ', '­čĺž', 238),
  ('gazvez', 'V├şz-g├íz szerel┼Ĺ', '­čĺž', 239),
  ('zenesz', 'Zene / Zenetan├ír', '­čÄÁ', 240),
  ('zenetermelo', 'Zenei producer / Hangst├║di├│', '­čÄÜ´ŞĆ', 241),
  ('zenekar', 'Zenekar / Party DJ', '­čÄÁ', 242),
  ('zoldseges', 'Z├Âlds├ęges / Hofladen', '­čŹÄ', 243);

-- Total categories: 244
